### ISSUE TITLE
Add AtomicMpscChunked implementation

### ISSUE THREAD

**Issue by guidomedina** [JCTools/JCTools#101]
The variants like:
- `XpxcGrowableArrayQueue`
- `XpxcUnboundedArrayQueue`

Don't look too appealing to me, but that's just my opinion, Netty will soon welcome `MpscChunkedArrayQueue` and will soon need a `MpscAtomicChunkedArrayQueue` and maybe a `SpscChunkedArrayQueue`

I also think having these variants only will make JCtools way more appealing to other APIs as they will soon realize they will use all the variants because all of them are useful.

To resume, I think JCtools should focus on:
- `XpxcLinkedQueue` and its atomic variant - done?
- `XpxcArrayQueue` and its atomic variant - done?
- `XpxcChunkedArrayQueue` and its atomic variant - incomplete.

**Comment by nitsanw** [comment]
I'm not sure what the ticket is about... is it one of the following?

* Tidy up SpscGrowable/Unbounded and setup a clear class hierarchy for it and Chunked
* We need an Atomic variant of Chunked queue

Is there more? I have a potential contributor looking at tidying up the SPSC chunked situation, I'll open an issue for it.

**Comment by guidomedina** [comment]
@nitsanw I didn't know there was a ticket for that already, I meant something similar to what you have stated except that I meant to completely replace `Unbounded` and `Growable` for `Chunked` which IMHO is the real deal and add their atomic counterparts

That way JCtools will be very consistent, symmetric and more appealing (not saying that it is not appealing but having it like that will make it a most have for other APIs) in what it offers.

**Comment by nitsanw** [comment]
Given that refactoring excercise is tracked in #107 I've renamed to reflect the need for an atomic variant.
The ultimate goal would be to generate all the atomic queues, as per #104

**Comment by nitsanw** [comment]
#166 is now tracking the development of the request here, closing
