### ISSUE TITLE
Unify base implementation for SPSC growable/unbounded/chunked

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#103]
Most of the code is common to either implementation (base data structure/most methods). The difference lies in the resize implementation.
This should also serve as a good opportunity for eliminating an accidental differences and cleaning up and simplifying the implementation.

**Comment by akarnokd** [comment]
The trouble I see with such unification is how it will affect the JIT. As far as I understand, JIT looks at things at class level and thus can profile and inline a regular and an unbounded version separately. If they are combined then all use places now have a single class with probably more conditional branches, uncommon traps and perhaps megamorphic dispatches.

**Comment by georges-gomes** [comment]
Another case for code generation maybe.
Cherry on the cake: Keeps the jar smaller.

**Comment by nitsanw** [comment]
@akarnokd absolutely valid concern, but I think this can be worked around with some compiler awareness (wait for the self-help styled book to appear in the hippy book shop soon!)
The 3 implementation should be the same in all but the implementation of the 'offerSlowPath'. This method is not meant for inlining, since we would generally want the inlining method to inline anything else first. As long as the cold path is cold the economy should extend to any overhead caused by the existence of multiple implementations. Note that this is only a concern if the JVM can't assume a single implementer. This is a run time analysis (CHA) so as long as you only load a single implementor of the 3 there should be no overheads.
