### ISSUE TITLE
Use code generation to create atomic queue classes

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#104]
This will be made easier by normalizing all queue code to access fields and arrays via the load/store methods(lp/lv/sp/so/sv/cas/xchg/xadd). In theory the atomic variants will then be the same logic super imposed on a different data structure (where the accessors are not Unsafe). This should also pave the way towards JDK9 VarHandles type implementations.

**Comment by nitsanw** [comment]
This would remove the overheads of maintaining an ever growing range of queues, and the likelihood of forgotten fixes etc.

**Comment by nitsanw** [comment]
@akarnokd since the atomic package was largely your contribution, please comment on this ticket regarding your thoughts. I'm hoping to refactor the code to a state where the accessors are all in the parent classes allowing a clean swap of parent to generate atomic variants, is that over optimistic?

**Comment by akarnokd** [comment]
I see two issues/challenges:

1) You have to parameterize over the storage: `T[]` vs `AtomicReferenceArray<T>`.

2) Queues that loop in offer/poll, you'd want to read the AtomicLong object into some local variable to save on the reference load (too much volatile around, not sure JIT would do it anyway). The current implementation suffers this as well.

**Comment by nitsanw** [comment]
> I see two issues/challenges:
> 
> 1) You have to parameterize over the storage: T[] vs AtomicReferenceArray<T>.
> 
I thought I'd leave the buffer load there, have it a noop in the atomic case and extends the AtomicRefArray
> 2) Queues that loop in offer/poll, you'd want to read the AtomicLong object into some local variable to save on the reference load (too much volatile around, not sure JIT would do it anyway). The current implementation suffers this as well.
> 
I am leaning towards atomic field updaters instead of atomic longs.
We should measure the impact, perhaps we'll need a bigger codegen hammer
