### ISSUE TITLE
Should 'atomic' queues package be a separate jar?

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#105]
Since library users may have concerns with the size of the jar, would splitting the atomic queues to their own jar make sense?
I'm not sure this is a big deal since the library is rather small IMO, but maybe useful some other people?

**Comment by guidomedina** [comment]
If you take into account that shade plugin purges non-used classes maybe it isn't worth the effort.

**Comment by guidomedina** [comment]
Well, for library users (not shaded API users) it might be worth.
