### ISSUE TITLE
Provide library shading examples for 'single-jar'/'no-external-deps' type users

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#106]
This will make the lives of library writers using JCTools easier and may encourage a default starting point other than Copy & Paste.
See relevant discussions in the tickets tracked under #100

**Comment by guidomedina** [comment]
Can I send a PR with an example of shade plugin usage in JCtools README?

**Comment by raphw** [comment]
Its really quite trivial to shade a dependency as a Maven module within your project: https://github.com/raphw/JCTools/commit/dec83b6bf5158181b90d36149d65b4f9d00ceb44

**Comment by guidomedina** [comment]
You are missing one useful configuration parameter `minimizeJar = true` which purges non-used classes from the shaded package.

**Comment by raphw** [comment]
You can do that but I would not necessarily recommend that. The Maven Shade plugin (and Gradle's wrapper around it) only include classes that are referenced in the shadowed artifacts. This breaks all use of reflection, if any. JCTools is fairly small already.

**Comment by guidomedina** [comment]
I know, but we know JCtools doesn't use reflection (at least for now), I have seen people almost crying for few extra classes which is why if we document how to shade it, we should at least mention that it can be done with JCtools, as an optional step.

**Comment by guidomedina** [comment]
And add the fact that it adds up, a project can have many dependencies, if each dependency carelessly shade within tidying up you will potentially end up with a high percentage of unnecessary extra classes.

**Comment by guidomedina** [comment]
Junit tests should detect these cases for such dependency, if I use Netty for example which will shade JCtools, they have unit tests which will detect such case.

In my current project I use JCtools, Netty is used also, same as Akka and others, imagine 4 of them use JCtools shade, and none without a proper clean up of extra classes, I (the end user) end up with extra classes I don't need, see my point?

**Comment by nitsanw** [comment]
I'll add a new repo for JCTools fo it, I'd like to get maven and gradle samples under it, so it will have it's own top level readme for motivation and a separate per example readme.
Like most things its trivial once you know how to do it...

**Comment by nitsanw** [comment]
Repo added with simple all-in-one examples in and placeholders for shading samples:
https://github.com/JCTools/ShadeJCToolsSamples
