### ISSUE TITLE
Consider Standardizing Names

### ISSUE THREAD

**Issue by pjulien** [JCTools/JCTools#117]
The queues and channels have standard names, e.g., ``MpmcArrayQueue`` and ``SpscLinkedAtomicQueue``, but new types and contributions found in the experimental package deviate from this standard.

- Sets are found in ``org.jctools.maps`` but others are found in ``org.jctools.sets``
- Considering #83, the use of "NonBlocking" might get convoluted over time.
- For ``NonBlockingHashSet`` and ``SingleWriterHashSet``, I am arguing that these names are not has approachable than the existing JCTools scheme of ``MpMcHashSet`` and ``SpMcOpenHashSet``.  Or perhaps ``MwMrHashSet`` and ``SwMrOpenHashSet`` since these aren't queues?

In any case, the existing JCTools naming scheme should not be undervalued, it's very concise.

**Comment by normanmaurer** [comment]
+1

**Comment by nitsanw** [comment]
@pjulien Thanks for the feedback.
The naming scheme in experimental is loose, it's a place for ideas and in progress features so I'm OK with names going different way there. I have considered the Map/Set naming question and face the following:

 1. There's generally no upside to single reader, so it's a Sw/Mw prefix maybe.

**Comment by pjulien** [comment]
@nitsanw 

> so it's a Sw/Mw prefix maybe.

I think that would be great

**Comment by nitsanw** [comment]
Closing since I don't think I have any further action on this until the classes are considered for core.

**Comment by nitsanw** [comment]
Now the classes have moved to core, this needs reconsideration before 1.3 release

**Comment by nitsanw** [comment]
I've settled on keeping the maps package and the NBHM class name. Consistency and naming are important, but so is mind share and existing users. I think relocating NBHM to JCTools should strive for minimal changes, and while I don't like the name I'm also of the opinion that changing it will confuse people more than delight them.
@pjulien thanks for bringing this up, I would have gone your way if this was a new creation, the naming will be used for the single writer map/set implementations to come.
