### ISSUE TITLE
SpscGrowableArrayQueue !isEmpty() but poll() == null

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#119]
We've run into this problem with the Spsc queue over in a C# port and now in [RxJava](https://github.com/ReactiveX/RxJava/issues/4004).

When the queue gets offered, the producerIndex [gets updated before](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/BaseSpscLinkedArrayQueue.java#L157) the element is written, therefore, a consumer thread checking `isEmpty()` may get false but the subsequent `poll()` returns `null`.

In the regular SpscArrayQueue, it's [the opposite](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/SpscArrayQueue.java#L129).

**Comment by guidomedina** [comment]
I think RxJava is still using a copy & paste version of _-probably-_ an old version of these classes, Netty recently shaded JCtools into it to avoid such approach, I would check first if current JCtools still have such issues and then shade it into RxJava.

There are other resolved issues not related with this one that RxJava can benefit from by shading JCtools.

I know @nitsanw was pursuing such goal with RxJava team.

**Comment by akarnokd** [comment]
@guidomedina This is why I first checked JCTools master where I found the inconsistency within JCTools itself. See the links to the JCTools source in my post. If it were a matter of outdated RxJava copies, I wouldn't have come here but simply updated our version.

**Comment by guidomedina** [comment]
yeah, same approach we followed for Netty, I didn't explained it properly, we first found the issue, identified it here, fixed it and shaded it.

**Comment by guidomedina** [comment]
Sorry for brevity also, typing from office ;-)

**Comment by mjpt777** [comment]
JCTools could take this approach I added to Agrona that addresses the issue and makes for less cache missing when data is available.

https://github.com/real-logic/Agrona/commit/d7139680a81c23c6e380421236443450cd96d615

**Comment by nitsanw** [comment]
@akarnokd thanks for reporting. This looks easily fixable by reversing the lines. I'll have a closer look at the code and fix shortly.

@mjpt777 The approach you describe would in this particular case leave peek/poll/isEmpty consistent, but they would be inconsistent with size(). So not a cure for this bug. You raise a nice point on the economics of isEmpty() and who might be likely to call it. The index based variant treats it like you would size(), your version takes a consumer bias which is interesting.
