### ISSUE TITLE
MpscArrayQueue.offerIfBelowTheshold is broken: offering is still possible when queue is full

### ISSUE THREAD

**Issue by m-anthony** [JCTools/JCTools#120]
I tried to use this method to avoid false sharing between producers and consumer when queue is full (I want to consider that the queue is full if available space is less than 2 cache lines), however the invariants of the queues do not hold: with a capacity of 256 * 1024 elements, i had (according to a heap dump once producers threads have been shut down):
- consumerIndex = 125,430,983
- producerIndex = 346,180,420
- producerLimit = 797,633

=> The "queue is full" test in this queue is probably wrong to have such figures

Moreover, the javadoc of this method is messy, and I'm not sure of what should the threshold parameter be:
- the description of the method said that the threshold is the minimal availability for the offer to be successful
- the description of the threshold parameter said that it is the maximal size for the offer to be successful

Finally, there is a typo in the method's name

**Comment by nitsanw** [comment]
This method has been contributed, so the style and doc are understandably different from the rest of JCTools. Having said that, bugs and doc errors should have been picked up in the review.
Looking at the code I must agree the doc is confusing and the method name is misspelt. This is used by at least one user of JCTools to the best of my knowledge, so changes must be done carefully, but it must change.
A further look at history shows a bug was introduced in a refactoring moving from using a wrapPoint calculation to using a producer limit. Fixing now.

**Comment by nitsanw** [comment]
Please review the javadoc/retest. This is an issue that has been introduced in JCTools 1.2, will be fixed in the up and coming release 1.3.

**Comment by nitsanw** [comment]
To be absolutely fair, I think the lacking tests and vague javadoc are to a large part responsible for the error made in refactoring here.

**Comment by nitsanw** [comment]
@m-anthony thanks for reporting

**Comment by nitsanw** [comment]
@kay @ettoremaiorana please review also

**Comment by m-anthony** [comment]
I had a look on the fix, it seems OK. My code that previously failed into an infinite loop on producer side is now working fine.

Thank you very much

**Comment by nitsanw** [comment]
@m-anthony good to hear. Does the javadoc (latest) better explain the usage?

**Comment by m-anthony** [comment]
Yes it does. In the 1.2 version, the name was already good enough to understand the usage, but now there is no more contradiction in the javadoc and the fixed code is easy to understand so it's perfectly clear

**Comment by nitsanw** [comment]
@m-anthony Good :)

**Comment by ettoremaiorana** [comment]
+1
