### ISSUE TITLE
Why does the SpSc impl requires two ordered stores?

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#123]
The SpScArrayQueue uses two ordered stores. However, I do not understand why the  [first one](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/SpscArrayQueue.java#L128) is important. Unfortunately, there is no explaination in the code except "StoreStore".
I think it is sufficient to store the producer index in an ordered way to also make the element visible for the consumer. What am I missing?

**Comment by akarnokd** [comment]
I'm not an expert on this like Nitsan but here is my understanding: 1) prevent that store to move further up (too early and gets too inconsistent with size/isEmpty()), 2) make sure the emptiness/fullness checking (aka fast-flow) works properly as they form aquire-release pairs.

**Comment by ChristianWulf** [comment]
Thanks for your quick answer. Can you give an example (for 1) when a reordering could cause problems? Unfortunately, "works properly" is not enough for me to understand your second point. 

@nitsanw It would be great if you could add a more expressive comment to this line of code.

**Comment by nitsanw** [comment]
There are 2 reasons to use the ordered store:

 1. ordering of stores
 2. atomicity of longs

The elements in the array form a happens before relationship between offer and poll. So the nulling out in poll, and new value store are married to the volatile loads in those methods observing availability of data/space in the queue.
The index stores need to be atomic, so must use an ordered store.
The index stores must come after the element stores to provide an !isEmpty() -> poll() != null relationship. 
It is possible to marry the index stores with a volatile load to form the ordering between offer and poll but relying on element value is faster (compare the inlined counter versions of SPSC in experimental)
@ChristianWulf I am not sure how much documentation is ideal in these methods, and must admit other examples in this domain are rather minimalistic (see JDK/Disruptor/Agrona). I am open to suggestions though, so please keep asking and express your understanding in a PR which will make this better.
