### ISSUE TITLE
Support for OSGi desired or opposed?

### ISSUE THREAD

**Issue by CodingFabian** [JCTools/JCTools#126]
Hi,
I just noticed that the jctools-core jar does not provide the required manifest entries, which would allow it to be used in osgi. Right now one would rebundle it to use it.
Are you guys opposed against adding some manifest entries? There is a maven plugin which does this automatically.
If you would accept a PR, I can have a look what would the best way for jctools to generate the manifest entries.

**Comment by nitsanw** [comment]
There's no opposition, but I'm not clear on what is required for it to work.
If you send a PR that would be a great way to find out :)

**Comment by nitsanw** [comment]
fixed with #127
