### ISSUE TITLE
How to best model a queue that starts dropping old events when full?

### ISSUE THREAD

**Issue by alexandru** [JCTools/JCTools#139]
Hi,

I need some sort of fixed-size buffer that when full starts dropping old events in order to make room for new ones. 

I was thinking that one possible solution would be to use a [MpmcArrayQueue](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java). And I need `MPMC`, even though I only have a single consumer, because when the queue is full the producer(s) could also consume, so on `offer` for dropping old events I could do it like this:

```java
while (!queue.offer(elem)) queue.poll()
```

Is this problematic? Is it stupid? :-)

I also don't understand the advantages of [ConcurrentCircularArrayQueue](https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/ConcurrentCircularArrayQueue.java). Is this like some sort of ring buffer? Would it be better for this problem?

If these questions are annoying, please tell me and I'll stop :)

**Comment by nitsanw** [comment]
A Queue is a well defined interface. This is not what it does.
What your describe is more of a rolling buffer where it is the consumer's responsibility to catch up and should they fall behind they will experience loss. Detecting the gap in messages and dealing with it will need implementing etc.
JCTools at the moment does not include this kind of class, but Aeron IPC offers this functionality, if only for sending raw binary data(no references).

**Comment by mjpt777** [comment]
Aeron IPC does not drop when the subscriber does not keep up. Just to correct ;-)

**Comment by nitsanw** [comment]
@mjpt777 My bad, shoud have double checked. I thought you had a data structure that fit the bill in Aeron, or am I mixing discussion with reality here?

**Comment by alexandru** [comment]
Thanks for your input @nitsanw. I have already implemented variations, like dropping incoming messages, or starting to apply back-pressure, on top of queues. You know how they say, when you've got a hammer ... 😊 Having a "*drop old events on overflow*" option is nice to have, but as I suspected, hard to implement efficiently and out of my league.

Cheers,

**Comment by mjpt777** [comment]
@nitsanw Maybe you are thinking about the [BroadcastBuffer](https://github.com/real-logic/Agrona/tree/master/src/main/java/org/agrona/concurrent/broadcast) that comes in Agrona. Aeron does make use of it for communicating from the driver to clients. It is not used in normal Aeron IPC.

**Comment by juddgaddie** [comment]
@alexandru perhaps this is what you are looking for https://nickzeeb.wordpress.com/2013/03/07/the-coalescing-ring-buffer/
