### ISSUE TITLE
Drop JDK 6 support?

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#140]
I'll give this time to ferment, if no objections arise we shall move on to JDK7

**Comment by akarnokd** [comment]
Will shading with Java 6 projects work after that?

**Comment by nitsanw** [comment]
no, since the compile target will be incompatible. Please let me know if this is a deal breaker for your library. This is not something I plan to do suddenly.

**Comment by akarnokd** [comment]
You advocated for shading for RxJava 1.x some time ago https://github.com/ReactiveX/RxJava/issues/1735 but nobody worked it out and even so, we'd be unable to follow JCTools after this change. RxJava 2.x queues [were aligned](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/queue/SpscArrayQueue.java#L40) with internal optimizations and there are incompatible with any shading. In other words, this won't really affect RxJava. Project Reactor 3 is Java 8 and there shouldn't be any problem later if they decide to shade. There are discussions for Reactor 4 to target Java 9 and thus VarHandles, therefore, neither the Unsafe nor the Atomic versions of current will be an option for shading.

**Comment by normanmaurer** [comment]
@nitsanw netty still supports java 6 :(

**Comment by nitsanw** [comment]
@akarnokd I did advocate shading, and indeed RxJava did not shade and maintain their own copy. If RxJava is 1.6 compatible I will be inclined to stay compatible for longer. 
@normanmaurer I hear you.
 Do you have an EOL date you are considering?

**Comment by guidomedina** [comment]
@normanmaurer have you thought of the following?
- 4.0.x -> Java 6+
- 4.1.x -> Java 7+
- 5.0.x -> Java 8

I saw a Netty discussion regarding versions and I think I proposed that to move smothly, that said, maybe if such approach is adopted, we could have JCtools 2.x for Java 7 and maybe JCtools 3.x for Java 8.

Just an idea...

**Comment by nitsanw** [comment]
@guidomedina I am more inclined towards branching and denoting differentiation in artefact name, so:
jctools-core-jdk6/7/8/9
version: X (so v2.9 on all jdk versions is the same API, but impl and build may differ).
The version number scheme seems too easy to misinterpret IMO.
@akarnokd @normanmaurer what do you think?

**Comment by akarnokd** [comment]
Sounds great to me. Would you also consider splitting by Unsafe vs. Standard as well (Java 9 could then unify both into a single implementation again)?

**Comment by nitsanw** [comment]
@akarnokd I don't know anyone who does that... what would be the benefit beyond jar size?

**Comment by akarnokd** [comment]
For example, to avoid the temptation of using Unsafe-based queues because an intermediate library exposes JCTools in full.

**Comment by nitsanw** [comment]
@akarnokd I hear you. Problem is that atomic package is very limited ATM. I can't do this without offering better compatibility (all queues, maps, same interfaces) so you can truely use it as a safe drop in. So for now the package split will have to remain. People can achieve the effect you describe via selective use of shading in their build.

**Comment by normanmaurer** [comment]
@nitsanw actually not worry about netty. We compile with java7 and can just fallback to non jctools queues when we detect java6 at runtime. I don't worry to much about performance impact with java6 as people should upgrade anyway.

**Comment by alexandru** [comment]
Having just experienced the joy of supporting Android (see https://github.com/monix/monix/issues/269), I would like Java 6 support to continue if possible, although I perfectly understand why you'd want to drop it.

At this point I'm thinking of forking the classes I need from `jctools-core` for internal usage, with proper attribution and licensing of course.

**Comment by nitsanw** [comment]
@alexandru I generally prefer people to shade a direct dependency rather than copy and paste. It will be an understandable choice if JDK6 support was violently terminated, but that's not the plan.

**Comment by nitsanw** [comment]
Given feedback on this ticket and elsewhere JDK6 support removal will be reconsidered post JDK9 release but is not on the cards ATM.
