### ISSUE TITLE
ConcurrentCircularArrayQueue.toString() produced UnsupportedOperationException

### ISSUE THREAD

**Issue by normanmaurer** [JCTools/JCTools#143]
```java
java.lang.UnsupportedOperationException
	at org.jctools.queues.ConcurrentCircularArrayQueue.iterator(ConcurrentCircularArrayQueue.java:73)
	at java.util.AbstractCollection.toString(AbstractCollection.java:454)
	at java.lang.String.valueOf(String.java:2994)
	at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:331)
```

I think this is true for your other implementations as well. Should be good enough to just override the `toString()` method until you want to implement `iterator()` (which is most likely never ;)).

**Comment by nitsanw** [comment]
:) I'm surprised this bug has been hidden so long, obviously nobody is calling toString on JCTools queues.

**Comment by normanmaurer** [comment]
Nobody except the scala REPL 😜

**Comment by nitsanw** [comment]
Fixed with:
https://github.com/JCTools/JCTools/commit/c01347344c39e576e2c522707474679fe3013276
https://github.com/JCTools/JCTools/commit/cd5fec0a096b4b9a5d4589f32991f36663395733
