### ISSUE TITLE
javadoc doesn't express proper semantics for drain with limit

### ISSUE THREAD

**Issue by devinrsmith** [JCTools/JCTools#144]
https://github.com/JCTools/JCTools/blob/635475824dc2daf76ab2b25cf318a4f8ccc4a47c/jctools-core/src/main/java/org/jctools/queues/MessagePassingQueue.java#L208

**Comment by nitsanw** [comment]
I'm almost certain you know what you mean... but I don't. Can you be a bit more explicit? what would be the wording you'd use? what does "proper" mean in this context?

**Comment by devinrsmith** [comment]
There doesn't seem to be any `limit` in the javadoc example, thus the javadoc code is not semantically equivalent to expected method.

**Comment by nitsanw** [comment]
OK, that makes sense :-)
Thanks for reporting, I'll fix shortly.
