### ISSUE TITLE
Add support for JDK9 VarHandles as alternative to using sun.misc.Unsafe

### ISSUE THREAD

**Issue by jvz** [JCTools/JCTools#145]
[JEP 193](http://openjdk.java.net/jeps/193) is adding `VarHandle` which provides a standard way of using all the Unsafe methods currently used in JCTools as far as I can tell. With that in mind, I believe that said Unsafe methods will be removed (or at least hidden in a module that requires a command line argument to use) in JDK10. Utilising a [multi-release jar](http://openjdk.java.net/jeps/238), this support can be added either by wrapping usage of Unsafe/VarHandle and having alternative implementations of that class, or by providing alternative implementations of classes using Unsafe/VarHandles directly.

**Comment by nitsanw** [comment]
This is going to become a priority as and when JDK9 is out the door, but is certainly going to happen.
At this point I'm not sure what the best packaging option is, be it as a separate releasable jar or via the multi-release option you describe.
A PR demoing the approach will be very helpful.

**Comment by nitsanw** [comment]
Should be a relatively small effort to generate the VarHandles versions now?

**Comment by felixbarny** [comment]
Did you already make a decision pro/con multi-release jars? Does anyone know if multi-release jars are working with `javaagent`s and the maven shade plugin? I suspect there will be complications along the way... Also, It would require a lot of code duplication on your side. If wrapping the usage of Unsafe/VarHandle and using the appropriate strategy according to the current JM's capabilities is feasible, that would probably be the cleanest solution.

I'm currently in search for a future-proof and Java 7 compatible high-performance concurrent queue. But none of disruptor, Agrona or JCTools seem to be prepared for Java 11, which will already be released in about three months from now.

**Comment by felixbarny** [comment]
Hm, actually it seems like you already did something like this with the `Atomic` variants of the queues. Could you explain when you would use one over the other? It seems like the `AtomicReferenceArray` uses var handles internally/Unsafe internally. Are the non-atomic versions faster because it does not have to do as many runtime checks?

**Comment by nitsanw** [comment]
@felixbarny We currently have the `Atomic` variants generated from the `Unsafe` versions for all the queues. This is to allow users in environments where `Unsafe` is not available to use the same algorithms with as little indirection as we can manage using the `Atomic` updaters and `AtomicReferenceArray`. We could notionally extend the code generation to produce `VarHandle` variants, but this work would have to coincide with an effort on the build side that would make a multi-release jar. This has not happened yet.
I have tested JCTools with JDK9 and JDK10 (and I think an EA of JDK11, but not sure), it works fine AFAIK. I don't think access to Unsafe has changed in JDK11, but perhaps I'm out of touch?

**Comment by felixbarny** [comment]
I thought I read somewhere that they were going to encapsulate Unsafe in Java 11. But now I can't find the source anymore.

In your experience, what is the performance difference of the Atomic vs the Unsafe queues?

**Comment by felixbarny** [comment]
I just tested jdk-11-ea+18 and `MpscArrayQueue` still works fine. I might have confused [the removal of Unsafe#defineClass](http://jdk.java.net/11/release-notes#b06) with the complete removal of `Unsafe`.

**Comment by jvz** [comment]
Right, as I mentioned originally, they're not removing Unsafe, just standardizing functionality and hiding the Unsafe implementations. I don't see that class ever fully disappearing unless the Java language adds syntactical equivalents.

**Comment by nitsanw** [comment]
see #157
