### ISSUE TITLE
Queues for Primitive Values

### ISSUE THREAD

**Issue by sirinath** [JCTools/JCTools#154]
Sometimes you need queues for primitive values. So it is possible to add primitive specialised queues.

**Comment by nitsanw** [comment]
This is a problematic proposition with current Queue interface which relies on "null" meaning. It therefore implies designing a new interface. The usecase is covered at the moment by the experimental channels, see if that helps your cause. Please provide a concrete usecase, and let me know if you have considered alternatives etc.

**Comment by sirinath** [comment]
What I am worried is the penalties. For each case what would be the optimal. The question is can there be a SPSC or any other type of queue which is the most optimal for the use case. I am not sure if channels will fit this when you want more juice from granularity of the type of use. Maybe you can redefine the null meaning for primitive queues and perhaps they can all be generated from one template.

**Comment by nitsanw** [comment]
I'm still not clear on what you want and how the usecase is generally appealing. Please spend some time on providing a strong usecase. There are many things that CAN be done, the question is always if they are worthwhile doing (in this case consider the investment: coding/testing/maintenance etc etc).

**Comment by RichardWarburton** [comment]
An approach taken in Agrona is to implement the queues as int specialised, then generate other versions from them. By having the template be the int version it makes things pretty easy to test and debug, whilst still getting the benefit of templating.

**Comment by nitsanw** [comment]
I don't see this happening. Closing.
