### ISSUE TITLE
[Question] Suggestion for work distribution using MPSC or mesh of SPSC

### ISSUE THREAD

**Issue by haint504** [JCTools/JCTools#155]
I am currently working on a work scheduler which has a dedicated thread pool to execute work. I am using concurrent queue to push work item (a Runnable instance) to one of these threads in thread pool. There are multiple producers to push the work item to thread pool. There are two approaches to do this:
1. Each thread has dedicated MPSC queue. For each work item, using an Atomic counter to choose the next thread in thread pool to push that work item to its MPSC queue. The thread does polling the queue to get the work item and run it.
2. The main thread in thread pool maintains an MPSC, there is one SPSC from this thread to other threads in the pool. All work items are pushed to that MPSC, but for each work item polled, the thread do load balancing (using an plain counter, not the Atomic one) to push the work item to one of other threads in thread pool.
My wonder is: Which way is better in term of performance?
Thank you.

**Comment by nitsanw** [comment]
It depends...
For generic work scheduling, unless the tasks a re very small and uniform, you are likely to want work stealing for a scheduler. You are contrasting a scheduler with a 'coordinator' to an MPSC for each thread in the pool. Even with a coordinator some sort of handoff to workers is needed, so some kind of SPSC queue. You could use an MPSC to coordinator and a much shorter SPSC per worker to get some work stealing when a particular worker queue is full, or you could have a scheme where threads alternate between being workers and coordinators. It a complex set of trade offs in terms of cost, ordering, throughput and latency...
To begin with, why not start simple with an MPMC, spend time on modelling your loads and determining where bottlenecks my lie (maybe the queue is not the issue), then circling back to a more complex scheme if needed. I recommend you start with a clear measurement/target in mind, that will ultimately be the best guide in making these choices.

**Comment by haint504** [comment]
The tasks are quite small, in fact each task just do some serialization and send the serialized data to NIO socket channel. To increase the parallelism, I am trying to open multiple connections per destination host, one per selector. To some extents, this is quite similar to Netty's NioEventLoopGroup which is quite similar to former approach that I mention above. However, my experiment shows that the latter approach has higher performance, also higher latency :(

**Comment by nitsanw** [comment]
I am happy to have a look if you have a relevant workload/JMH. Closing this ticket for now.
