### ISSUE TITLE
Start a JDK9 branch to review pros/cons/pain of replacing Unsafe usage with VarHandles

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#157]
VarHandles replace Atomic*Updaters as the inlined field volatile access tools with extra juice. It would be good to start a branch of JCTools which will explore the impact of replacing ALL Unsafe usage with VarHandles.
It might be beneficial in future to template generate 3 versions of all code(Unsafe/Atomic/VarHandles) to reduce the maintenance overheads.

**Comment by nitsanw** [comment]
@akarnokd yes, I expect you are right :-(
There's no good way for the compiler around this, barring somehow realizing the mask is in fact the same a s length-1 which happens in another method entirely and requires the compiler to track all write to that field etc. In theory this is not such a big deal as we trade length load with a field load, length might be open to false sharing (depending on layout decisions by JVM).
The real issue IMO is the impending maintenance nightmare of keeping all these versions in-line and the complexities around releasing them etc. As long as Unsafe is around it is ironically the most "write once run everywhere" option.

**Comment by nitsanw** [comment]
@akarnokd @normanmaurer how would you handle per JDK jars as dependencies?

**Comment by DavidGregory084** [comment]
@nitsanw JDK9 offers [multi-release JAR files](http://openjdk.java.net/jeps/238), although I'm not sure how Maven support for these is coming along

**Comment by ktoso** [comment]
FYI, you can pull multi release jars off pretty easily, did it here if you'd need inspiration; https://github.com/ktoso/akka-streams-jdk9-strawman-mvn/blob/master/README.md

Problem is that you're then stuck with maintaining 2 almost-the-same impls of stuff most likely.

**Comment by nitsanw** [comment]
Based on the work delivered by @kay it should be easy to generate the VarHandles variants.
I'll have a look at the multi-release jar at some point. Its not very high on my list, but if anyone is very excited about this I'm happy to take on PRs.

**Comment by nitsanw** [comment]
I have done some initial tests and explorations here. This is not worth doing as long as Unsafe remains the most backwards compatible AND stable(performance wise) option of the currently available options. In tests I have thus far seen a clear win for Unsafe and no advantage in VarHandles over AtomicF**

**Comment by ben-manes** [comment]
Would it make sense to support Unsafe but implement a fallback to VarHandles? This way if unsafe is not allowed (e.g. via jlink) then it will not fail due to `NoClassDefFoundErrors`, as the user requested it to be hidden. However, for most applications, they can continue to use the more optimal method.

This could be achieved by a strategy interface per class and statically initializing to the appropriate implementation. For example, `MpscGrowableArrayQueue` could have a private interface `MpscAccess` that implements methods like `lvProducerIndex`. Then it would try to load `UnsafeMpscAccess` but fallbacks to `VarHandleMpscAccess` if needed. The JIT should inline the method calls so there shouldn't be a performance cost. I did this for Caffeine's `StripedBuffer` and am about to start on its embedded copy of `MpscGrowableArrayQueue` for a v3 release.

Or do you think this wouldn't be worth the effort?

**Comment by franz1981** [comment]
Hi @ben-manes, I've given a brief look at `Probe` on https://github.com/ben-manes/caffeine/blob/v3/caffeine/src/main/java/com/github/benmanes/caffeine/cache/StripedBuffer.java#L95 and AFAIK, given that is referenced in a static final field it should be fine perf-wise ie without getting any stealthy type guard check, but I still would like to verify it first; do you already have evidence of this in some benchmark (with `perfasm`)?

**Comment by ben-manes** [comment]
Sorry, I have not gotten to that yet. I agree it would be very good to verify.

**Comment by nitsanw** [comment]
We are still supporting JDK6. Some of this can be done via multi-release jars, some through SPI like tricks (interfaces/subclassing etc), but TBH we have had no complaints from users so far. Netty for instance will just use JDK queues if they can't use Unsafe. So, while I think this is something we might be able to solve, I'm reluctant to spend time on it without a clear need.

**Comment by ben-manes** [comment]
Yep, that’s reasonable to me. I’ll port the class that I am embedding for compatibility. Some Caffeine users have asked for removing unsafe and this is my only remaining case that could use a graceful fallback.
