### ISSUE TITLE
ScParkTakeStrategy question about visibility

### ISSUE THREAD

**Issue by Scottmitch** [JCTools/JCTools#160]
Can someone explain why the volatile variable write in `ParkTakeStrategy` [1] in isolation is sufficient to ensure the `offer` is not re-ordered to occur before the `unpark`? For example the typical "happens before" relationship requires some sort of association between multiple operations (e.g. read/write to the same variable).

For additional context see related discussion on the original PR [2][3].

[1] https://github.com/JCTools/JCTools/blob/master/jctools-experimental/src/main/java/org/jctools/queues/blocking/ScParkTakeStrategy.java#L18
[2] https://github.com/JCTools/JCTools/pull/46#r22962260
[3] https://github.com/JCTools/JCTools/pull/46#issuecomment-70052936

**Comment by nitsanw** [comment]
IIRC this is a hack to get a full fence in, not a HB relationship as such. Could be replaced with a Unsafe.fullFence, but since JCTools aims at JDK6 compatibility we don't have this in place. cc @georges-gomes

**Comment by maxwindiff** [comment]
Thanks @nitsanw for explaining. To be pedantic, does this rely on JVMs doing the sane thing, i.e. emitting the fence after volatile stores instead of before loads?

**Comment by Scottmitch** [comment]
Is an isolated volatile write on a public member variable guaranteed to introduce a full fence (or provide similar guarantees on all platforms)? There may be a few layers of rules used to derive this conclusion but it would be appreciated if you could provide more details :)

For example the cookbook seems to indicate that a volatile store followed by a volatile load will not be re-ordered (in general) (see the `Can Reorder` table), but there it is possible the isolated usage could be "demoted" to a normal write:

>  If a compiler can somehow (usually only with great effort) prove that a lock is only accessible from a single thread, it may be eliminated. Similarly, a volatile field provably accessible from only a single thread acts as a normal field.

However is the assumption that because the member variable is public that the JIT would not be able to make this optimization, or couldn't effectively un-do the optimization if it is later determined to be invalid (e.g. if a new class is loaded that accesses the public field, or reflection)?

What about adding a "noop" read of the volatile in the consumer thread after `park` but before `poll`. Based on the statement below (from the cookbook) this seems to be a more prudent way to ensure the ordering. Let me know if there is another rule which may provide a loop hole in this case.

> Even if a compiler optimizes away a field access (for example because a loaded value is not used), barriers must still be generated as if the access were still present.

[1] http://gee.cs.oswego.edu/dl/jmm/cookbook.html

**Comment by nitsanw** [comment]
@maxwindiff it relies on the JMM, or rather my understanding of it.
@Scottmitch I agree it would be good to add the read in the consumer side, if only for clarity.

**Comment by Scottmitch** [comment]
> if only for clarity.

I agree it clarifies things, but without this read isn't it open to interpretation how the JVM implementation may behave? Can you provide a reference to where the current isolated volatile write guarantees ordering?

**Comment by nitsanw** [comment]
The cookbook reference you provide essentially covers it: "Even if a compiler optimizes away a field access (for example because a loaded value is not used), barriers must still be generated as if the access were still present."

**Comment by maxwindiff** [comment]
@nitsanw But the cookbook also says:

> ### Removing Barriers
>
> ... But this strategy can be improved in at least the following ways:
>
> - Removing barriers that aren't needed because there is no possibility that multiple threads could rely on them; for example volatiles that are provably visible only from a single thread. Also, removing some barriers when it can be proven that threads can only store or only load certain fields. All this usually requires a fair amount of analysis.

From this example it seems Graal is able to optimize unobserved volatiles away: https://shipilev.net/blog/2016/close-encounters-of-jmm-kind/#wishful-unobserved-volatiles

(I understand the cookbook is not the spec, but it seems the volatile can be optimized away either we follow the cookbook to the word or not.)

**Comment by nitsanw** [comment]
@maxwindiff good point.

**Comment by georges-gomes** [comment]
Hi Scott, Nitsan,

I'm very late to the discussion - I'm sorry - I think you got it already.
I have done this a long time ago but this is how I thought about it:

The volatile write will instruct the compiler to push data into memory and
wait for it to be "visible" to other threads at this point.
All this before the "unpark()" because the volative will avoid reordering.
You really only want to "unpark()" once everything is in memory - visible
by other threads - obviously.

The major reason is to cope with "lazySet()" in the queue slots because
they could be visible later.
(lazySet() push the data to memory queues but doesn't wait for full
processing into memory)

Could the volatile write be optimized away? Honestly, I don't know...  but
having the "storeFence" in public visibility makes this optimization pretty
dangerous and complex for the compiler/runtime. IMHO.

I hope this helps.
Kind regards
Georges
