### ISSUE TITLE
Visibility of queue.offer in presence of a volatile?

### ISSUE THREAD

**Issue by alexandru** [JCTools/JCTools#162]
I have a:

```java
volatile boolean upstreamIsComplete = false
```

This gets set on the producer side at some point to true:

```java
queue.relaxedOffer(elem)
upstreamIsComplete = true
```

On the consumer side I have a loop that does the following test:

```java
while (true) {
  A next = offer.relaxedPoll()
   
  if (next != null) { 
    // ... 
  }
  else if (upstreamIsComplete) {
    // Race condition check
    if (queue.isEmpty) {
      // finish stuff
      // ...
      return
    }
  }
}
```

The problem I have is that I've got cases where that last event isn't visible. So even though I have that race condition check, after seeing `upstreamIsComplete == true`. I assumed that after `upstreamIsComplete` is seen as true, then everything in that `queue` should be published, since `upstreamIsComplete` is a volatile.

Mentions:

- the queue I'm using is a `MpscUnboundedArrayQueue`
- in the test I'm doing I have a single producer and a single consumer, but the consumer has asynchronous boundaries

So the actual question: can this happen, or do you think there's a greater possibility that I have a bug in my code?

Thanks,

**Comment by nitsanw** [comment]
do you have a reproducer?
In theory, assuming the upstreamIsComplete is indeed only ever fired once you should have a HB edge here based entirely on the volatile read/write.
So in theory, observing:
upstreamIsComplete +  queue.isEmpty
Should mean no other writes to the queue are possible. This should work even if the queue was broken, so I'm inclined to think this is bug in your code elsewhere, you can guard the upstreamIsComplete writes and the queue writes to find the culprit. Anther alternative is to test with different queue types and see what happens.

**Comment by alexandru** [comment]
@nitsanw thanks, that's what I thought too, but I'm always unsure in matters of the JMM ... I have async boundaries and some ordering logic might be faulty (i.e. that last offer might happen after the volatile write, but I don't understand why).

Closing this.

**Comment by akarnokd** [comment]
This is a common mistake. If `upstreamIsComplete` comes after any previous offer, you have to read `upstreamIsComplete` before checking for `isEmpty` or evaluating `poll()`. This has been extensively proved in [RxJava 2](https://github.com/ReactiveX/RxJava/blob/2.x/src/main/java/io/reactivex/internal/operators/flowable/FlowableObserveOn.java#L374).

**Comment by nitsanw** [comment]
@akarnokd but the loop above does that, it optimistically polls before, but if the flag is set and the queue is not empty it'll read again.

**Comment by alexandru** [comment]
Right, the problem I might have is that my last `offer` might come after the volatile write - but had to ask in order to make sure the JMM agreed :-)

Thanks guys for the input.
