### ISSUE TITLE
[Feature] SpscLinkedQueue to support max capacity

### ISSUE THREAD

**Issue by Scottmitch** [JCTools/JCTools#164]
`SpscGrowableArrayQueue` and `SpscChunkedArrayQueue` enforce a max capacity limit, but require `Unsafe`. `SpscLinkedQueue` appears to be the no-`Unsafe` alternative but doesn't provide a max capacity limit. Are there objections with enhancing `SpscLinkedQueue` to enforce a max capacity limit? Are there any plans on adding this functionality, or another no-`Unsafe` resizable spsc queue?

**Comment by nitsanw** [comment]
Generally speaking, all the queues in the queues package use Unsafe. Some alternative non-Unsafe implementations are available in the atomic package, but the list is incomplete. I urge you to port and PR the SPSC linked array queues if they are of value to you.

**Comment by nitsanw** [comment]
Closing as a question, please open a particular impl port request. There's no plan for a bounded capacity pure linked queue impl.

**Comment by Scottmitch** [comment]
`SpscLinkedQueue` should have been `SpscLinkedAtomicQueue`and has been corrected above.

Just to clarify the focus was on a no-`Unsafe` non-fixed size spsc queue with a max capacity. Pure linked is not necessary. However I got my answer .... no plans and PR please 👍
