### ISSUE TITLE
Wait Strategy and Documentation

### ISSUE THREAD

**Issue by eliasbalasis** [JCTools/JCTools#167]
Any direction on "wait strategy" to use with JCTools queues?

Any explanation or documentation on the different types of JCtools queues and ways to use each?

**Comment by nitsanw** [comment]
Is this helpful on which queue to use?
https://github.com/JCTools/JCTools/wiki/Which-Queue-Should-I-Use%3F

**Comment by eliasbalasis** [comment]
Thanks,

It helps more to understand Bounded/Unbounded, ArrayQueue/LinkedQueue differences and memory footprint impact

What I don't understand is "relaxedPoll" and "drain/fill" (batch read/write)

The final concern is wait strategy for consumers (batch or not).
How should a consumer effectively wait until the queue is not empty?

I hope this helps

**Comment by nitsanw** [comment]
This explains MPQ I hope:
https://github.com/JCTools/JCTools/wiki/What's-a-MessagePassingQueue%3F-Should-I-Use-It%3F

**Comment by eliasbalasis** [comment]
I understand that  relaxedPoll/relaxedOffer is the preference due to dramatic contention reduction.

I have been aligned with the wait strategy approach.

Are there more good stuff pages like this? Please add to wiki if you have more.

**Comment by eliasbalasis** [comment]
Too many queue variants still, which is good stuff.

Any particular or more detailed explanation for each type? (Array/Linked/Growable/L1/L2 etc.)

**Comment by nitsanw** [comment]
Please refer to the javadoc and package level javadoc for more specifics. I will enumerate the queues at some point on the wiki.
The padding classes are for false sharing protection and not part of the public API, they are also quite obviously not queues ;-).

**Comment by eliasbalasis** [comment]
Thanks for helping, I will study and may get back to you with specific questions.
