### ISSUE TITLE
Consider using Coveralls.io

### ISSUE THREAD

**Issue by maseev** [JCTools/JCTools#170]
I noticed that JCTools is using a cobertura maven plugin for gathering test coverage data. It would be great if JCTools could integrate with [Coveralls](https://coveralls.io/) and share its code coverage data on the main page. The integration itself is rather simple and consists of the following steps:

- Add the necessary maven plugins for test coverage (here's a simple [example](https://github.com/maseev/narwhal/blob/master/pom.xml#L44))
- Edit your .travis.yml by adding the following [section](https://github.com/maseev/narwhal/blob/master/.travis.yml#L7)
- Link your project with Coveralls (you can authenticate via Github account) and grab a badge which will show you the test coverage percentage every time your master branch gets updated
- Place this badge in the README.MD file, for example

**Comment by nitsanw** [comment]
Sounds good, I'll give it a go sometime :)

**Comment by nitsanw** [comment]
OK, I never got round to it... :(
PR maybe?

**Comment by maseev** [comment]
No problem. I'll have a look.
