### ISSUE TITLE
Consider using Github templates for pull requests and issues

### ISSUE THREAD

**Issue by maseev** [JCTools/JCTools#171]
I think it would be great if JCTools could use this [feature](https://github.com/blog/2111-issue-and-pull-request-templates) in order to add some structure to pull requests and issues. Folks from [Netty](https://github.com/netty/netty/issues/6074) project are using it, for example.

WDYT?

**Comment by nitsanw** [comment]
So, I'm of the mindset that volume can justify rules/optimizations, but in the absence of volume it can be hard to set the right rules. There's not that much traffic on JCTools, so I don't see the benefit of code style/issue templates etc. Perhaps one day...
Do you feel JCTools can benefit from this feature? are the issues too chaotic?

**Comment by maseev** [comment]
Yeah, you're probably right. It would be an overhead for those who are creating new issues and submitting PRs. No biggie. Closing for now.
