### ISSUE TITLE
Implement batching fill/drain methods on MpmcArrayQueue

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#180]
Current impl:
https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java#L330
Offers the API but is not actually batching the expensive operation which is the CAS. A better implementation would look ahead for a clear slot and attempt a batch CAS increment to it, followed by filling the slots up to, and including it (sequence checking each one).

**Comment by franz1981** [comment]
@felixbarny any feedback on this? Would like to know if the perf now looking good for batched ops on mpmc :)

**Comment by felixbarny** [comment]
I have still not implemented the batching yet 😬 
I also need to order a bare metal machine with more cores in order to properly do multi-threaded microbenchmarks.

**Comment by franz1981** [comment]
@felixbarny No worries: it means that the feature is there when you need it ;)
