### ISSUE TITLE
Compute for NonBlockingHashMap atomic/thread-safe?

### ISSUE THREAD

**Issue by u6f6o** [JCTools/JCTools#199]
I intended to use compute on the NonBlockingHashMap but realised that it has no implementation of its own but refers to the ConcurrentMaps default implementation.

In the classes javadoc there is following paragraph: "It provides identical correctness properties as ConcurrentHashMap.  All operations are non-blocking and multi-thread safe, including all update operations."

Is this true for the compute method as well?

**Comment by nitsanw** [comment]
From the javadoc:
```
     * <p>This implementation assumes that the ConcurrentMap cannot contain null
     * values and {@code get()} returning null unambiguously means the key is
     * absent. Implementations which support null values <strong>must</strong>
     * override this default implementation.
```
NBHM does not allow `null` keys/values, and is therefore not *required* to implement this method.

**Comment by henri-tremblay** [comment]
One note about this: @nitsanw you are right. However, the behaviour is a little bit different from the `ConcurrentHashMap`. So that might be surprising for some. In `ConcurrentHashMap`, the `remappingFunction` is called under lock. It is (obviously) not the case for CBHM.
