### ISSUE TITLE
Document performance characteristics of SpscChunked/Growable on wiki

### ISSUE THREAD

**Issue by brettwooldridge** [JCTools/JCTools#204]
Thanks for the project.

While the [Which Queue Should I Use?](https://github.com/JCTools/JCTools/wiki/Which-Queue-Should-I-Use%3F) wiki page is useful.  There are still subtlties that are not adequately explained; and it would be awesome if they could be added to that page.

For example, what are the performance differences/trade-offs between ``SpscChunkedArrayQueue`` and ``SpscGrowableArrayQueue``?

**Comment by nitsanw** [comment]
Can you please provide a list of your question to more concretely direct the "subtlties that are not adequately explained"?
Thanks

**Comment by brettwooldridge** [comment]
@nitsanw Clearly there is a difference between ``SpscChunkedArrayQueue`` and ``SpscGrowableArrayQueue``, otherwise two separate classes wouldn't exist.  However, it is not at all clear what those differences are.  Does one have higher throughput?  Does one use less memory?  Etc.

Additional explanation/documentation would be useful in helping users choose which is best for a given situation.

**Comment by nitsanw** [comment]
Between the update to the wiki and the improved javadoc I think this is resolved.

**Comment by brettwooldridge** [comment]
@nitsanw Thanks.
