### ISSUE TITLE
Why is SparsePaddedCircularArrayOffsetCalculator.allocate allocating an extra 2x the buffer pad?

### ISSUE THREAD

**Issue by youzhagui2006** [JCTools/JCTools#212]
public static <E> E[] allocate(int capacity) {
        return (E[]) new Object[(capacity << SPARSE_SHIFT) +
                                PaddedCircularArrayOffsetCalculator.REF_BUFFER_PAD * 2];
    }

why need  PaddedCircularArrayOffsetCalculator.REF_BUFFER_PAD * 2

**Comment by franz1981** [comment]
The pad is on both sides of each ref array to avoid false sharing with the rest of the heap
