### ISSUE TITLE
Why the paddings between the indexes are 17 long fields instead of 7?

### ISSUE THREAD

**Issue by yueru-mylove** [JCTools/JCTools#214]
As I learning the source code of MpscChunkedArrayQueue, there are 18 Long fields(144 bytes)  to pad the cache-line. But, the cache-line of the OS is always 32 bytes or 64 bytes(8 Long fields). Why does here use 144 byte?

**Comment by nitsanw** [comment]
The padding is 15 longs e.g. [here](https://github.com/JCTools/JCTools/blob/cfd5ae885f6074f0f6bb1489ac79b12bec9eab30/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java#L34):
```
    long p01, p02, p03, p04, p05, p06, p07; // 7 longs
    long p10, p11, p12, p13, p14, p15, p16, p17; // 8 longs
```
While cache line length is usually 64b (8 longs), the [Adjacent Cache-Line Prefetch](https://software.intel.com/en-us/articles/optimizing-application-performance-on-intel-coret-microarchitecture-using-hardware-implemented-prefetchers) is also commonly on, resulting in an effective cache line length of 128b.

**Comment by nitsanw** [comment]
The padding is 15 longs e.g. [here](https://github.com/JCTools/JCTools/blob/cfd5ae885f6074f0f6bb1489ac79b12bec9eab30/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java#L34):
```
    long p01, p02, p03, p04, p05, p06, p07; // 7 longs
    long p10, p11, p12, p13, p14, p15, p16, p17; // 8 longs
```
While cache line length is usually 64b (8 longs), the [Adjacent Cache-Line Prefetch](https://software.intel.com/en-us/articles/optimizing-application-performance-on-intel-coret-microarchitecture-using-hardware-implemented-prefetchers) is also commonly on, resulting in an effective cache line length of 128b.

**Comment by franz1981** [comment]
I can see that MpscChunkedArrayQueue has 16 long fields ie 128 bytes to pad the queue fields, not 18.
128 byte is the prefetching size (on x86 "modern" intel CPUs), hence just using 64 byte wouldn't be sufficient to pad optimally the fields.
For actual numbers please take a look at here: http://psy-lob-saw.blogspot.co.za/2013/10/spsc-revisited-part-iii-fastflow-sparse.html.
In particular look for the comparison between Y8 and Y83 which compare 2 identical queues except for the padding size(64 vs 128).

**Comment by yueru-mylove** [comment]
Got it! Thank you so much. sir. @nitsanw .
