### ISSUE TITLE
Why org.jctools.jmh.counters.CountersBenchmark only test with single Thread.

### ISSUE THREAD

**Issue by lexburner** [JCTools/JCTools#215]
Will it be better to use @GroupThreads(n) with JMH?

**Comment by lexburner** [comment]
I just feel curious about the performances within AtomicLong, LongAdder , ConcurrentAutoTableCounter , in multiple threads competition.

**Comment by nitsanw** [comment]
The benchmark is setup to use thread groups (as per the `@Group` annotation on the methods and the state annotation on the class). The minimum threads it would use is 2 by default, bu you can have more by setting the `-t` options from the command line.

**Comment by lexburner** [comment]
@nitsanw Hi，l read one post written by you [Advice for the concurrently confused: AtomicLong JDK7/8 vs. LongAdder](http://psy-lob-saw.blogspot.com/2014/06/jdk8-update-on-scalable-counters.html) . In my opinion，Jdk1.8 AtomicLong  also need a CAS operation
```
public final long incrementAndGet() {
    return unsafe.getAndAddLong(this, valueOffset, 1L) + 1L;
}
```
deep into `unsafe.getAndAddLong`
```
    public final long getAndAddLong(Object var1, long var2, long var4) {
        long var6;
        do {
            var6 = this.getLongVolatile(var1, var2);
        } while(!this.compareAndSwapLong(var1, var2, var6, var6 + var4));

        return var6;
    }
```
Is there `LOCK XADD` ?

I feel sorry to ask the question here, but i do not know how to contact you.

**Comment by lexburner** [comment]
I think it is the reason `branch prediction` that result in the better performance if JDK1.8 AtomicLong.

you can reference [here](https://stackoverflow.com/questions/29249030/how-cas-related-changes-in-atomiclong-class-in-java-8-work)

**Comment by nitsanw** [comment]
JDK8 has Unsafe.getAndAdd intrinsic which translates to a LOCK XADD on x86. Look at the benchmark assembly output using perfasm.
