### ISSUE TITLE
Size of queue may more then max size +1

### ISSUE THREAD

**Issue by yangyi438** [JCTools/JCTools#216]
I found a bug earlier this year

Seems to be

spscArrayGrowableQueue  

init give the max size 

but can run code make the queue = max +1

i truly run test code find it ,it is existence  
in Special cases

**Comment by nitsanw** [comment]
Can you be more specific? give a test case?

**Comment by yangyi438** [comment]
import org.jctools.queues.SpscGrowableArrayQueue;

/**
 * Created by yangyi438 on 2018/9/2.
 */
public class TestError2 {
    public static void main(String[] args) {
        int q = 0;
        SpscGrowableArrayQueue<Integer> queue = new SpscGrowableArrayQueue<Integer>(8, 32);
        for (int i = 0; i < 33; i++) {
            queue.offer(q++);
        }
        for (int i = 0; i < 7; i++) {
            Integer poll = queue.poll();
        }
        for (int i = 0; i < 14; i++) {
            Integer poll = queue.poll();
        }
        for (int i = 0; i < 80; i++) {
            queue.offer(q++);
        }
        int counot = 0;
        while (true) {
            Integer poll = queue.poll();
            if (poll != null) {
                counot++;
            } else {
                break;

            }
        }
        if (counot > 32) {
            throw new Error();
        }
    }
}

this code is 

        <dependency>
            <groupId>org.jctools</groupId>
            <artifactId>jctools-core</artifactId>
            <version>2.1.2</version>
        </dependency>

I debug carefully for reasons
It looks like index is the wrong calculation
There will be a value of null in the array
I forgot the exact reason. It's been months since I found out
You can debug see detail and fix it

**Comment by nitsanw** [comment]
Thanks for the test case, and sorry for the long silence.
I have reproduced the issue and working on a solution but have been very busy.

**Comment by yangyi438** [comment]
Jctools is the best concurrency library and we admire you and appreciate your contributions in your busy schedule
