### ISSUE TITLE
MpmcAtomicArrayQueue visibility issues under Java 7?

### ISSUE THREAD

**Issue by felixbarny** [JCTools/JCTools#217]
I'm using the `MpmcAtomicArrayQueue` to back my object pool implementation in the Elastic APM Java agent. A user-reported issue seems to indicate that two successive calls to `poll()` from two different threads return the same object instance (instead of removing the object from the queue). See https://github.com/elastic/apm-agent-java/issues/178#issuecomment-416515887
This only happens sporadically, which indicates a visibility issue.

The user's runtime environment is Java 1.7.0_141 (Oracle Corporation) on Linux 4.9.0-7-amd64.

Are you aware of issues in `MpmcAtomicArrayQueue` under this Java version?

**Comment by nitsanw** [comment]
Are you on latest version? The atomic queues are auto-generated from the Unsafe versions, so a bug in one would be the same in the other. Having said that, there have been no issues with the implementation AFAIK.

**Comment by felixbarny** [comment]
I'm on version 2.1.2. I suspect the bug not to be in JCTools but rather in the `AtomicReferenceArray` implementation of 1.7.0_141.

**Comment by felixbarny** [comment]
It does not seem to be an issue with JCTools. Sorry for the noise.
