### ISSUE TITLE
Queues based on Unsafe#getAndAdd instead of CAS spins?

### ISSUE THREAD

**Issue by felixbarny** [JCTools/JCTools#226]
Hi,

I'm learning about lock-free and wait-free algorithms and I was asking myself whether queues could be implemented based on the wait-free `Unsafe#getAndAdd` method as opposed to the lock-free CAS spin. The latter can still lead to queuing effects, especially under high contention and when there are more threads than processors concurrently doing the CAS spin.

Example of a CAS spin in `MpmcArrayQueue`:
https://github.com/JCTools/JCTools/blob/6b8feeaa913c780fd560943cf2d0d8f0af8461c2/jctools-core/src/main/java/org/jctools/queues/MpmcArrayQueue.java#L175-L176

Would it be possible to restructure the algorithm to be wait-free or is that inherently impossible?

Thanks,
Felix

**Comment by felixbarny** [comment]
Cool, thanks for the link! Is there a paper or a presentation somewhere which explains the algorithm? Are there plans for an Mpmc variant?

**Comment by franz1981** [comment]
@felixbarny Not at short term, considering that this version is just experimental (even if quite stable now). @nitsanw maybe has something in mind, I can't say :)

Re the algorithm is commented and explained on the code and is a (now huge) variation of the Aeron publication log buffer: https://github.com/real-logic/aeron/wiki/Data-Structures.
Any differences from the orgiinal version introduced by me or @nitsanw are undocumented in any article/paper AFAIK, but the *core* design is quite similar to the Aeron original data structure.

**Comment by franz1981** [comment]
@felixbarny I suppose you should be interested into https://github.com/JCTools/JCTools/pull/230
