### ISSUE TITLE
MpscUnboundedXaddArrayQueue enhancements

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#243]
I'm leaving here some notes on the new MpscProgressiveChunkedQueue:

1. freeBuffer buffer could be replaced by a simplified version of SpscArrayQueue 
2. there are edge cases where there is a lot of wasted space if compared to other cas based mpsc queues ie consumerBuffer has just the last item left to be consumed 
3. batch drain/fill has poor performance
4. OOM protection seems not easy to be implemented 
5. Missing doc to explain the differences from MpscCompoundQueue 
6. No Atomic implementation available

**Comment by nitsanw** [comment]
Tidying up, I think compound tickets like this one are not good for tracking/visibility. I'll close it and @franz1981 please file as separate tickets if you still want them.
Thanks!
