### ISSUE TITLE
Why there is no relaxedPoll in SpmcArrayQueue

### ISSUE THREAD

**Issue by TheLudlows** [JCTools/JCTools#251]
I want to poll from SpmcArrayQueue,and i want to get things from queue relaxed, to be honest ,want to get fast.but  there is no relaxedPoll in SpmcArrayQueue

**Comment by nitsanw** [comment]
https://github.com/JCTools/JCTools/blob/72c55e5bee5ed05e47c5f997f8d4bc9d736659d1/jctools-core/src/main/java/org/jctools/queues/SpmcArrayQueue.java#L274

?

**Comment by nitsanw** [comment]
Perhaps you are wondering why it just delegates to `poll()`?

**Comment by TheLudlows** [comment]
> 也许你想知道为什么它只是代表`poll()`？

tks for you reply,the relaxedPoll() in the SpmcArrayQueue what invoke poll() directly,sure

**Comment by franz1981** [comment]
@TheLudlows 
It means that the relaxed versionl has not been implemented on it because it can't (AFAIK)

**Comment by nitsanw** [comment]
@TheLudlows sometimes there's nothing to relax. The `poll` here does not have the spin loop you'll find elsewhere which can be eliminated by `relaxedPoll`
