### ISSUE TITLE
Consumed element nulling inconsistency between MPSC impls?

### ISSUE THREAD

**Issue by njhill** [JCTools/JCTools#252]
I noticed that `BaseMpscLinkedArrayQueue` and `MpscBlockingConsumerQueue` use `soElement(buffer, offset, null)` but `MpscArrayQueue` uses `spElement(buffer, offset, null)`, and could not think of a reason for the difference.

I know for correctness plain is fine so assumed if the `so` is intentional it must be GC-related, but then why the inconsistency?

**Comment by franz1981** [comment]
> I know for correctness plain is fine so assumed if the so is intentional it must be GC-related, but then why the inconsistency?

IIRC both the queues make use of `consumerIndex` release on producer side to wide the `producerLimit` so they could both make use of `spElement` on consumer side without breaking anything IMO.
I don't see particular reasons for this difference, sometime it just happens: performance wise there is a very small difference (if none TBH) between the 2s and I think is a change that can be proposed without breaking anything :+1:
