### ISSUE TITLE
MpscArrayQueue not being fully drained

### ISSUE THREAD

**Issue by dankraw** [JCTools/JCTools#253]
Hello,
we're using the `MpscArrayQueue` implementation in our project and lately we've been 
dealing with some pretty annoying bug that turned out to be related to `drain()` method of the queue.

What we've realised is that [drain(Consumer<E> c)](https://github.com/JCTools/JCTools/blob/v2.1.2/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java#L436) method might not return all items that were offered to the queue. It drains the queue only [until first null element is found in the buffer](https://github.com/JCTools/JCTools/blob/v2.1.2/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java#L471).
As described [here](http://psy-lob-saw.blogspot.com/2014/07/poll-me-maybe.html) :) there may be some other items left after the null element.

What we did as a quick poor man's solution was writing [our own implementation](https://github.com/allegro/hermes/pull/1032/files#diff-58179d888377a9bf9170c02006782e73R33) that makes use of the available MpscArrayQueue's public API.
The `size()` method tells us how many items there are when we call `drain()`.
The `poll()` method spin-waits when null element is encountered, but gives us confidence that all items are drained eventually.

Is the `drain()` behaviour on purpose or it should be considered a bug?

Regards,
Daniel

**Comment by franz1981** [comment]
Nope, is not a bug: it is supposed to behave like that :)

**Comment by dankraw** [comment]
Ouch, I wish there was similar comment added to MpscArrayQueue's when we were looking at it, but I understand that's just an implementation of MessagePassingQueue interface and all implementations should apply. :)

Thanks for quick response and explanation. :thumbsup:
