### ISSUE TITLE
Create wiki page for the XADD algorithm

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#261]

**Comment by nitsanw** [comment]
On my TODO

**Comment by franz1981** [comment]
Let me reference this: https://github.com/franz1981/JCTools-wiki/tree/xadd_docs

**Comment by franz1981** [comment]
@nitsanw I was thinking to run some benchmarks to get some result to be attached to the doc.
https://github.com/JCTools/JCTools/blob/master/jctools-benchmarks/src/main/java/org/jctools/jmh/latency/MpqBurstCost.java seems fine to me, wdyt?

While https://github.com/JCTools/JCTools/blob/master/jctools-benchmarks/src/main/java/org/jctools/jmh/throughput/QueueThroughputBackoffNone.java is tricky for unbounded qs...

**Comment by franz1981** [comment]
@nitsanw I've added a new commit with some benchmark results here https://github.com/franz1981/JCTools-wiki/commit/f22983915bb8760155e5e5c9d8b49d215e0e3c4e

**Comment by franz1981** [comment]
@nitsanw I've added more benchmark results and a chart :)
That's my final effort on this, but eventual corrections after your review :+1:

**Comment by franz1981** [comment]
@nitsanw ping
I've run another benchmark ie QueueBurstCost with these paramteters:
```
for i in 1 2 3 4 5 6 7 8 9 10 11; do java -jar microbenchmarks.jar org.jctools.jmh.latency.QueueBurstCost.* -f 10 -t $i -p burstSize=100 -p qType=MpscUnboundedXaddArrayQueue,MpscUnboundedArrayQueue >> poll_100.txt; done
```
and the same environment of https://github.com/franz1981/JCTools-wiki/blob/xadd_docs/MpscUnboundedXaddArrayQueue.md#lies-damned-lies-and-benchmarks results.
The results I'm getting for the single producer case need some attention IMO, please take a look:
```
Benchmark                 (burstSize)  (consumerCount)  (qCapacity)                      (qType)  (warmup)  Mode  Cnt      Score     Error  Units
QueueBurstCost.burstCost          100                1       132000  MpscUnboundedXaddArrayQueue      true  avgt  100  10515.205 ± 358.729  ns/op
QueueBurstCost.burstCost          100                1       132000      MpscUnboundedArrayQueue      true  avgt  100   8763.145 ± 368.595  ns/op
```
While for the `MpqBurstCost` I was getting:
```
Benchmark               (burstSize)  (consumerCount)                      (qType)  Mode  Cnt     Score    Error  Units
MpqBurstCost.burstCost          100                1  MpscUnboundedXaddArrayQueue  avgt  100  5337.122 ± 16.853  ns/op
MpqBurstCost.burstCost          100                1      MpscUnboundedArrayQueue  avgt  100  6441.541 ± 32.471  ns/op
```
It seems to me that  xadd q `poll` could be either slower then the cas q or so faster that will find it empty most of the time, causing `lvProducerIndex` to check emptyness and preventing the xadd on `producerIndex` to be fast as it should be: any idea how to improve it? 
Given that the relaxed variant of the xadd q seem faster then the cas q and the only difference is the emptyness check, I would bet on the second hyphotesis, wdyt?

**Comment by franz1981** [comment]
In addition, I was thinking if it would worth to pre-allocate the total size of pooled chunks continuosly:
```
public MpscUnboundedXaddArrayQueue(int chunkSize, int maxPooledChunks)
    {
        chunkSize = Pow2.roundToPowerOfTwo(chunkSize);
        final int totalSize = chunkSize * (maxPooledChunks + 1);
        final E[] wholeBuffer = CircularArrayOffsetCalculator.allocate(totalSize);
        final AtomicChunk<E> first = new AtomicChunk(0, null, true, wholeBuffer, 0);
        soProducerBuffer(first);
        soProducerChunkIndex(0);
        consumerBuffer = first;
        chunkMask = chunkSize - 1;
        chunkShift = Integer.numberOfTrailingZeros(chunkSize);
        freeBuffer = new SpscArrayQueue<AtomicChunk<E>>(maxPooledChunks + 1);
        for (int i = 0; i < maxPooledChunks; i++)
        {
            final int startIndex = chunkSize * (i + 1);
            freeBuffer.offer(new AtomicChunk(AtomicChunk.NIL_CHUNK_INDEX, null, true, wholeBuffer, startIndex));
        }
    }
```

**Comment by franz1981** [comment]
I'm still convinced, by looking `MpscUnboundedArrayQueue` code that the perf difference for the single producer case depends by a better poll implementation (kudos to Nitsan re it):

- less pointer chasing: single E[] vs AtomicChunk->E[]
- more streaming: JUMP + next E[] both embedded into E[] and next the last consumed element

**Comment by franz1981** [comment]
@nitsanw I've just noticed that the mpmc xadd q has reached the point of singularity and on consumer-side use a complex enough mechanics that maybe deserve few words to be understood: do you want me to prepare a doc about that as well?
