### ISSUE TITLE
BurstCost aren't handling multi-consumers correctly

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#272]
MpqBurstCost and QueueBurstCost aren't handling correctly multi-consumer scenario: see https://github.com/netty/netty/pull/9078#issuecomment-485066059 for further explanations.

**Comment by nitsanw** [comment]
To capture the TL;DR from that thread, the benchmark assumes last message processed is sufficient for declaring the batch processed, but in an MC scenario this may not be true.
