### ISSUE TITLE
MpscLinkedQueue Spin Documentation and Strategy

### ISSUE THREAD

**Issue by DRayX** [JCTools/JCTools#274]
The comment at the top of MpscLinkedQueue seems to be inaccurate: it states that MpscLinkedQueue is a direct port of D. Vyukov's non-intrusive mpsc node based queue, but this isn't true as it adds a spin wait to the pop/poll operation which significantly alters the characteristics of the queue.  It may also be worth documenting the atypical use of an ordered store when updating next in put.  Cconsistency is guaranteed by the spin in the consumer as opposed to a StoreLoad barrier in the producer (thus improving the performance of the producer without changing the consistency guarantees of the queue).

The other thing is that it might be nice to support some sort of spin strategy.  While the spin wait in MpscLinkedQueue should be rare, it would be nice to allow the user to provide some idle strategy such as Thread.yield (probably too heavy) or Thread.onSpinWait (not support in Java8).

**Comment by franz1981** [comment]
> but this isn't true as it adds a spin wait to the pop/poll operation which significantly alters the characteristics of the queue

That's partially true: `BaseLinkedQueue::relaxedPoll` uses the same algorithm of D. Vyukov, while `MpscLinkedQueue::poll` uses the adapted version mentioned in the javadoc IIRC.
I agree with you that could be stated more clearly.

>  it would be nice to allow the user to provide some idle strategy such as Thread.yield (probably too heavy) or Thread.onSpinWait (not support in Java8).

I link a closed relevant issue: https://github.com/JCTools/JCTools/issues/147
And a relevant comment that's 100% in line with your request: https://github.com/JCTools/JCTools/issues/147#issuecomment-554226547

**Comment by nitsanw** [comment]
"it states that MpscLinkedQueue is a direct port of D. Vyukov's non-intrusive mpsc node based queue, but this isn't true"

The term `direct port` is not exactly legally binding. It's a direct port into Java, and `java.util.Queue` interface. As @franz1981 mentions we offer the relaxed semantics as well. But I take your point that this is a port with some differences which are worth mentioning. I'll give it a go when I have time, or you can help us out with a PR @DRayX ?

"atypical use of an ordered store when updating next in put."
This is harmless(on x86), and makes sense (to me at least) as a mirror barrier to the volatile load on the same field in `poll`. If this is killing your performance on a non-x86 arch let's talk about it.

"Consistency is guaranteed by the spin in the consumer as opposed to a StoreLoad barrier in the producer (thus improving the performance of the producer without changing the consistency guarantees of the queue)"
The spin on the consumer ensures we don't violate the `java.util.Queue` interface. If you want the relaxed semantics use `relaxedPoll`.

Thanks for reporting this!

**Comment by nitsanw** [comment]
Fixed by https://github.com/JCTools/JCTools/commit/15b12a18b8d129dbe57588ecc4dd032f4ab157d4
Please re-open/discuss further if insufficient @DRayX
