### ISSUE TITLE
Document code generators under jctools-build module

### ISSUE THREAD

**Issue by ceki** [JCTools/JCTools#275]
It's not easy to understand what the code generators under jctools-build are supposed to do. I think  one or two phases documenting their goal would be useful.

I am proposing to document these classes: 

- JavaParsingAtomicArrayQueueGenerator.java 	
- JavaParsingAtomicLinkedQueueGenerator.java 
- JavaParsingAtomicQueueGenerator.java

**Comment by nitsanw** [comment]
PRs welcome :-)

**Comment by ceki** [comment]
כדי להגיש כל דבר, הייתי צריך קודם להבין מה קורה כאן.
