### ISSUE TITLE
SpscLinkedQueue#offer implementation bugs

### ISSUE THREAD

**Issue by hl845740757** [JCTools/JCTools#292]
Recently, I decided to add Chinese comments to JCTools. When I read the source code of SpscLinkedQueue, the implementation of the offer caused me some confusion, because it may cause consumerNode newer than producerNode and cause bugs. Therefore, I wrote SpscLinkedQueueTest for verification, and an exception occurred.

The producer should publish the new producerNode first, and then ensure that it is reachable from the consumerNode.

```
        // final LinkedQueueNode<E> nextNode = newNode(e);
        // final LinkedQueueNode<E> preNode = lpProducerNode();
        // spProducerNode(nextNode);
        // preNode.soNext(nextNode);

        final LinkedQueueNode<E> nextNode = newNode(e);
        lpProducerNode().soNext(nextNode);
        spProducerNode(nextNode);
```

```
public class SpscLinkedQueueTest {

    private static volatile boolean stop = false;

    public static void main(String[] args) throws InterruptedException {
        SpscLinkedQueue<String> messageQueue = new SpscLinkedQueue<>();

        new Producer(messageQueue).start();
        new Consumer(messageQueue).start();

        try {
            Thread.sleep(10 * 1000);
        } finally {
            stop = true;
        }
    }

    private static class Producer extends Thread {

        final SpscLinkedQueue<String> messageQueue;

        long sequence = 0;

        Producer(SpscLinkedQueue<String> messageQueue) {
            this.messageQueue = messageQueue;
        }

        @Override
        public void run() {
            try {
                while (!stop) {
                    messageQueue.offer(Long.toString(sequence++));
                    Thread.sleep(1);
                }
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    private static class Consumer extends Thread {

        final SpscLinkedQueue<String> messageQueue;

        private Consumer(SpscLinkedQueue<String> messageQueue) {
            this.messageQueue = messageQueue;
        }

        @Override
        public void run() {
            while (!stop) {
                messageQueue.poll();

                if (!messageQueue.isEmpty()) {
                    final String e = messageQueue.poll();
                    if (null == e) {
                        throw new Error("MessageQueue.isEmpty() is false, messageQueue.poll() return null!");
                    }
                }
            }
        }

    }
}
```
Exception in thread "Thread-1" java.lang.Error: MessageQueue.isEmpty() is false, messageQueue.poll() return null!
	at com.wjybxx.fastjgame.concurrenttest.SpscLinkedQueueTest$Consumer.run(SpscLinkedQueueTest.java:84)

**Comment by hl845740757** [comment]
Same wrong implementation as offer
```
    @Override
    public int fill(Supplier<E> s, int limit)
    {
        if (null == s)
            throw new IllegalArgumentException("supplier is null");
        if (limit < 0)
            throw new IllegalArgumentException("limit is negative:" + limit);
        if (limit == 0)
            return 0;

        LinkedQueueNode<E> tail = newNode(s.get());
        final LinkedQueueNode<E> head = tail;
        for (int i = 1; i < limit; i++)
        {
            final LinkedQueueNode<E> temp = newNode(s.get());
            tail.soNext(temp);
            tail = temp;
        }
        final LinkedQueueNode<E> oldPNode = lpProducerNode();
        oldPNode.soNext(head);
        spProducerNode(tail);
        return limit;
    }
```

**Comment by hl845740757** [comment]
The implementation of **SpscArrayQueue** has the same error！

**Comment by franz1981** [comment]
PRs are welcome, beware a bug is something that prevent the correct functioning of the data structure:)

**Comment by hl845740757** [comment]
> PRs are welcome, beware a bug is something that prevent the correct functioning of the data structure:)

For a single consumer queue, the poll or peek should not return null if the queue is not empty.

**Comment by nitsanw** [comment]
Hi! thanks for joining the conversation and bringing this up :-)
We have a test that is supposed to cover this:
https://github.com/JCTools/JCTools/blob/264e669a8dd125e922a0fb6e08f31c42f7d07e53/jctools-core/src/test/java/org/jctools/queues/QueueSanityTest.java#L358
```
    @Test(timeout = TEST_TIMEOUT)
    public void testPollAfterIsEmpty() throws Exception
    {
        final AtomicBoolean stop = new AtomicBoolean();
        final Queue<Integer> q = queue;
        final Val fail = new Val();
        final Runnable runnable = new Runnable()
        {
            @Override
            public void run()
            {
                while (!stop.get())
                {
                    q.offer(1);
                    // slow down the producer, this will make the queue mostly empty encouraging visibility issues.
                    Thread.yield();
                }
            }
        };
        Thread[] producers = producers(runnable);
        Thread consumer = new Thread(new Runnable()
        {
            @Override
            public void run()
            {
                while (!stop.get())
                {
                    if (!q.isEmpty() && q.poll() == null)
                    {
                        fail.value++;
                    }
                }
            }
        });

        startWaitJoin(stop, producers, consumer);

        assertEquals("Observed no element in non-empty queue", 0, fail.value);

    }
```
And all the queues pass. I have run your test however and it does fail, which is worth looking into.
I'm on it :)

**Comment by hl845740757** [comment]
> Hi! thanks for joining the conversation and bringing this up :-)
> We have a test that is supposed to cover this:
> https://github.com/JCTools/JCTools/blob/264e669a8dd125e922a0fb6e08f31c42f7d07e53/jctools-core/src/test/java/org/jctools/queues/QueueSanityTest.java#L358
> 
> ```
>     @Test(timeout = TEST_TIMEOUT)
>     public void testPollAfterIsEmpty() throws Exception
>     {
>         final AtomicBoolean stop = new AtomicBoolean();
>         final Queue<Integer> q = queue;
>         final Val fail = new Val();
>         final Runnable runnable = new Runnable()
>         {
>             @Override
>             public void run()
>             {
>                 while (!stop.get())
>                 {
>                     q.offer(1);
>                     // slow down the producer, this will make the queue mostly empty encouraging visibility issues.
>                     Thread.yield();
>                 }
>             }
>         };
>         Thread[] producers = producers(runnable);
>         Thread consumer = new Thread(new Runnable()
>         {
>             @Override
>             public void run()
>             {
>                 while (!stop.get())
>                 {
>                     if (!q.isEmpty() && q.poll() == null)
>                     {
>                         fail.value++;
>                     }
>                 }
>             }
>         });
> 
>         startWaitJoin(stop, producers, consumer);
> 
>         assertEquals("Observed no element in non-empty queue", 0, fail.value);
> 
>     }
> ```
> 
> And all the queues pass. I have run your test however and it does fail, which is worth looking into.
> I'm on it :)

Since poll may return a value when the queue is empty, additional poll calls are required

**Comment by nitsanw** [comment]
`poll() == null` is a signal that queue is empty, so semantically there should be no difference. I think there's a barrier missing in the `poll` implementation (maybe in `offer` too) which allows the `isEmpty` code to be reordered with it in this direction.

**Comment by hl845740757** [comment]
> `poll() == null` is a signal that queue is empty, so semantically there should be no difference. I think there's a barrier missing in the `poll` implementation (maybe in `offer` too) which allows the `isEmpty` code to be reordered with it in this direction.

U got it

**Comment by nitsanw** [comment]
OK, the issue is really with `isEmpty`. For the `*ArrayQueue` the assumption is that `consumerIndex` can' pass `producerIndex`, but with the Fast Flow type of `poll` where the element presence is considered proof enough that progress is possible we can have `poll` increment the `consumerIndex` before the `offer` increments the `producerIndex`. The solution is easy, we just let the index comparison logic allow for that.

For the Linked case this is a bit more confusing, but I'm working on it :-)

**Comment by franz1981** [comment]
@nitsanw Just curious why the existing test hasn't shown that

**Comment by hl845740757** [comment]
For consumers, `consumerNode.next` may be visible before the `producerNode`.

**Comment by nitsanw** [comment]
@franz1981 please review the commit. I added relevant tests. The previous test was calling `poll` conditional on `isEmpty`, but the issue was with `poll` breaking the `isEmpty` invariant. In a sense it was gating the bad behaviour. I added several variants of tests and expanded the coverage to `peek` and the new MPQ methods of adding elements to the queue.

**Comment by nitsanw** [comment]
@hl845740757 thanks for reporting! great find :-) Please review the commit and comment.

**Comment by franz1981** [comment]
@nitsanw sure :)
@hl845740757 well done!!!!
