### ISSUE TITLE
Test cases should remove the dependency on QueueFactory/AtomicQueueFactory

### ISSUE THREAD

**Issue by hl845740757** [JCTools/JCTools#300]
Please forgive me for my bad english.

I think the current test cases are not from the user's perspective. 

For example, if there is a test case for testing the 'spsc' queue, then most of the queues should be tested because they can serve as "spsc" queue. The dependence on the factory will cause the test case to fail to cover all the queues.

```
    @Test(timeout = TEST_TIMEOUT)
    public void testFIFO() throws Exception
    {
        assumeThat(spec.isSpsc(), is(Boolean.TRUE));
        ....
    }
```

For another example, MpmcArrayQueue should pass the testSizeLtZero use case in MPMC, MPSC, SPMC and SPSC. However, the dependence on the factory results in test cases that do not cover all cases.
```
@Test(timeout = TEST_TIMEOUT)
    public void testSizeLtZero() throws Exception
    {
        ...
    }
```

**Comment by nitsanw** [comment]
The title and the comment don't match, can you please clarify?

**Comment by hl845740757** [comment]
@nitsanw I changed the description
