### ISSUE TITLE
why the producerBuffer field in the BaseMpscLinkedArrayQueueColdProducerFields not volatile

### ISSUE THREAD

**Issue by liujianhuiouc** [JCTools/JCTools#317]
```
private void resize(long oldMask, E[] oldBuffer, long pIndex, final E e) {
    int newBufferLength = getNextBufferSize(oldBuffer);
    final E[] newBuffer = allocate(newBufferLength);

    producerBuffer = newBuffer;
    final int newMask = (newBufferLength - 2) << 1;
    producerMask = newMask;

    final long offsetInOld = modifiedCalcElementOffset(pIndex, oldMask);
    final long offsetInNew = modifiedCalcElementOffset(pIndex, newMask);


    soElement(newBuffer, offsetInNew, e);// element in new array
    soElement(oldBuffer, nextArrayOffset(oldMask), newBuffer);// buffer linked
```

May I know the reason about the producerBuffer and the producerMask not be volatile or volatile put?
another producer in a different thread may not visit the last value of the producerBuffer in the poll method?

**Comment by liujianhuiouc** [comment]
@nitsanw Could you help me answer that question?

**Comment by nitsanw** [comment]
The mask and buffer fields are plain fields whose access(read/write) is validated on the producer index, which is volatile. The values are only changed inside and "exclusive lock" for which we use the lower bit of the producer index.

**Comment by liujianhuiouc** [comment]
Thanks a lot. IMO, the mask and buffer fields are placed on the same cache line with the producer index, so these will be validated along with the producer index, is right?

**Comment by nitsanw** [comment]
These fields are only safe to use once a producer has won the CAS for the producer index, this is unrelated to memory layout. Expected use is:
```
        while (true)
        {
            pIndex = lvProducerIndex();
            // lower bit is indicative of resize, if we see it we spin until it's cleared
            if ((pIndex & 1) == 1)
            {
                continue;
            }
            // pIndex is even (lower bit is 0) -> actual index is (pIndex >> 1)

            // mask/buffer may get changed by resizing -> only use for array access after successful CAS.
            mask = this.producerMask;
            buffer = this.producerBuffer;
            // a successful CAS ties the ordering, lv(pIndex) - [mask/buffer] -> cas(pIndex)
            // now we must determine if resize is required
            if (mustResize) {
              if (casProducerIndex(pIndex, pIndex + 1)) // lock mask/buffer
              {
                resize(); // safe to modify mask/buffer
                mask = this.producerMask;
                buffer = this.producerBuffer;
                soProducerIndex(pIndex + 2); // release other producers
                break;
              } else continue;
            }
            else if (casProducerIndex(pIndex, pIndex + 2))
            {
                break;
            }
        }
//... write element
```
The implementation has other optimizations/details, but the above is the core of the ordering. I hope that helps.

**Comment by liujianhuiouc** [comment]
Thanks for the thorough response. I still have a doubt that there exist, two producers, one producer executes at the line of 
```
      mask = this.producerMask;
      buffer = this.producerBuffer;
```
at the same time, another producer resizes, and the `this.producerMask` will be assigned to a new buffer. the first producer will redo the offer process because the pIndex has modified, but that might still get the previous this.producerMask which stale now, due to the producerMask is not visible at the thread(that has already modified by another thread)

**Comment by franz1981** [comment]
@liujianhuiouc I believe you should look at this: https://preshing.com/20130922/acquire-and-release-fences/
Acquiring and release semantics are what allow visibility to work as expected here.

**Comment by nitsanw** [comment]
The mask/buffer reads are conditional on the pIndex volatile read, and their use is conditional on the CAS, so they are consistent with the pIndex.

**Comment by liujianhuiouc** [comment]
got it, thank you
