### ISSUE TITLE
Counters experimental?

### ISSUE THREAD

**Issue by richardstartin** [JCTools/JCTools#321]
The counters in the experimental module look great - I would like to start using them and already have a dependency on jctools-core - are they mature enough to be moved over to the core module?

**Comment by franz1981** [comment]
You have my +1 here :)
Afaik the counters are in a good shape (see the original issue and pr on https://github.com/JCTools/JCTools/issues/36).
Please check the concurrency freak ones too on http://concurrencyfreaks.blogspot.com/2013/08/concurrency-pattern-distributed-cache.html

Just curious: what kind of exact use case are you trying to cover where LongAdder isn't enough?

**Comment by richardstartin** [comment]
`LongAdder` was introduced in JDK8.

**Comment by nitsanw** [comment]
I have not looked at them in a while. Can you describe your use case in slightly more detail?

**Comment by nitsanw** [comment]
moved to core

**Comment by richardstartin** [comment]
@nitsanw thanks very much, will there be a release soon?
