### ISSUE TITLE
Q: queue conflation

### ISSUE THREAD

**Issue by LarsKrogJensen** [JCTools/JCTools#325]
Any of the queues that support conflation, i.e. if a (keyed) entry already exists, replace it otherwise enqueue.

**Comment by franz1981** [comment]
Afaik nope. It's feasible if it's not ensured that a key cannot appear more then one time...

**Comment by LarsKrogJensen** [comment]
Ok, trying to decifer the _It’s feasible..._

**Comment by franz1981** [comment]
I see you've asked this same question on https://github.com/tools4j/nobark/issues/4 and I can answer you the same: Agrona many to many array queue === JCTools mpmc array q (and the xadd mpmc unbounded q too) is a good candidate to implement it ie right now isn't implemented.
This library is OSS and we love contribution so feel free to send a PR to address this and I'll happily review it ☺️

**Comment by LarsKrogJensen** [comment]
thanks, I will for sure look into it.
