### ISSUE TITLE
meme motif plot can not align same motif in different sequences

### ISSUE THREAD

**Issue by Zefeng-Wu** [JCTools/JCTools#332]
After I obtain the xml result from MEME suit, I want to visualize the motif distribution. JCtools is a good plotter, but  I want to align the same motif in different sequences to keep them in the same relative position by setting the sequences as the same length. Can the software do this? 
Besides, I noticed that the default result in MEME result ONLY show those true motif but without the predicted motifs. However, JC tools output all the motifs including true motif and predicted motif in the output. Can it be set?

**Comment by franz1981** [comment]
I'm not sure JCTools is a plotter, probably you're referring to other projects!
