### ISSUE TITLE
NonBlockingHashMapLong iterator.remove() not working on key=0 (NO_KEY)

### ISSUE THREAD

**Issue by matteobertozzi** [JCTools/JCTools#334]
Version: 3.2.0

Using a simple map as example with an item with a key = 0 (the NO_KEY),
operations like get(0) and remove(0) works as expected
```java
final NonBlockingHashMapLong<String> map = new NonBlockingHashMapLong<>();
map.put(123L, "hello");
map.put(456L, "world");
map.put(0L, "zero");
```

but trying to remove the NO_KEY via iterator() does not produce any exception, but the item is not removed.
```java
final Iterator<String> itValue = map.values().iterator();
while (itValue.hasNext()) {
  final String value = itValue.next();
  if (value.equals("zero")) {
    System.out.println("removing zero");
    itValue.remove();
  }
}
System.out.println(map); // {0=zero, 456=world, 123=hello}
```

```java
final Iterator<Long> itKey = map.keySet().iterator();
while (itKey.hasNext()) {
  final Long key = itKey.next();
  if (key == 0) {
    System.out.println("removing zero");
    itKey.remove();
  }
}
System.out.println(map); // {0=zero, 456=world, 123=hello}
```

```java
final Iterator<Entry<Long, String>> itEntry = map.entrySet().iterator();
while (itEntry.hasNext()) {
  final Entry<Long, String> entry = itEntry.next();
  if (entry.getKey() == 0) {
    System.out.println("removing zero");
    itEntry.remove();
  }
}
System.out.println(map); // {0=zero, 456=world, 123=hello}
```

Using directly the remove() works as expected
```java
String v = map.remove(0); // v=zero
System.out.println(map); // {456=world, 123=hello} 
```

**Comment by nitsanw** [comment]
Thanks for reporting, I'll look into it shortly!

**Comment by nitsanw** [comment]
This is a clear bug in NHBMLong:
https://github.com/JCTools/JCTools/blob/f58559b3e66ff841c750e390c63772d9a0b4ed74/jctools-core/src/main/java/org/jctools/maps/NonBlockingHashMapLong.java#L1044

We are removing directly from the CHM, but the CHM remove does not handle the special key `NO_KEY` (AKA `0L`). We need to do the same song and dance performed elsewhere for this special case.

The code is also a break with how NHBM works, which upon close inspection raises a further more general question we can tackle while here (@cliffclick please chime in if you have good answers to the below):

It would appear that iterators on NBHM take the view that a remove is conditional on the original value being mapped to the original key. This seems to be inconsistent for the `keySet` iterator at least, where the removal of a key can be argued to have the same semantics as `V remove(long key)`. The matching of both key and value would seem appropriate for `values` and `entrySet` iterators however.

I'm also not sure why the implementations don't call up to the `NBHM.this.remove()`/`NBHM.this.putIfMatch()` directly. It would seem to be a more readable implementation at the cost of a couple of loads (the `this` ref and the `kvs` ref).
