### ISSUE TITLE
Provide blocking peeks for MpscBlockingConsumerArrayQueue

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#337]
It should allow to implement batching draining strategies using a mix of blocking peek + drain 

eg
```java
// ...
do {
  while (q.blockingPeek(timeOut, unit) != null) {
      // same while using poll too
      if (q.drain(batch::offer, limit) > 0) {
          processBatch(batch);
      }
  }
  // perform timed check on something
} while (true); // or whatever other way to end this madness :P
```
Doing the same with the current API means using `take` or `poll` ie adding the just read `e` to the batch before using `drain` again, that's less "nice" (just a matter of taste, I know) and more verbose

**Comment by nitsanw** [comment]
I think that a `blockingPeek` doesn't make sense. I can see the appeal of a blocking drain though, which would seem to address the above better:
```
  while (q.blockingDrain(batch::offer, limit, timeOut, unit) != 0) {
          processBatch(batch);
  }
```
