### ISSUE TITLE
UnsafeRefArrayAccess is limited to specific scale and fails otherwise

### ISSUE THREAD

**Issue by moritz-bruder** [JCTools/JCTools#342]
https://github.com/JCTools/JCTools/blob/77a481cbebaa4ae02bfd9e8312be4b5259cb3c62/jctools-core/src/main/java/org/jctools/util/UnsafeRefArrayAccess.java#L37

Is there any reason why this should be limited to those specific values of `scale`?  In VMs that return different values for `sun.misc.Unsafe.arrayIndexScale` the code will always fail.

**Comment by nitsanw** [comment]
Any result other than 4byte/8byte pointer size is unexpected and should lead to failure. Do you have a particular case in mind where this is not a good check?

**Comment by moritz-bruder** [comment]
@nitsanw I have a VM that returns a value of 1 for any array class with `Unsafe.arrayIndexScale`.  The reason is that this VM uses a different way to address memory (not necessarily pointers).  This is a reasonable definition since it works consistently with the other methods and does not, to my knowledge, contradict the javadoc.

In my opinion it is therefore most reasonable to allow any value as suggested by the documentation of `Unsafe.getInt`:
```
     * <li>The object referred to by <code>o</code> is an array, and the offset
     * is an integer of the form <code>B+N*S</code>, where <code>N</code> is
     * a valid index into the array, and <code>B</code> and <code>S</code> are
     * the values obtained by {@link #arrayBaseOffset} and {@link
     * #arrayIndexScale} (respectively) from the array's class.  The value
     * referred to is the <code>N</code><em>th</em> element of the array.
```
I do not see how limiting this to certain implementations is in any way useful or correct.  Thus, use the two's logarithm of `Unsafe.arrayIndexScale` for computing `REF_ELEMENT_SHIFT` or drop the use of `REF_ELEMET_SHIFT` altogether and just use the equivalent multiplication and division.  (I do not see the advantage of using shifts here that do not get optimized to shifts anyway.)

**Comment by nitsanw** [comment]
A reference array is not an int array, it is therefore incorrect to use `Unsafe.getInt` to get a value from the array.

Can you provide more details about the VM in question? Have you made the change you request and ran a full build and test cycle on this VM?

> I do not see how limiting this to certain implementations is in any way useful or correct. [etc]

I like opinionated people, I am also opinionated :-)

Using shifts is consistent with the existent code. PRs are welcome if you think there's a better way to do anything.

**Comment by moritz-bruder** [comment]
> A reference array is not an int array, it is therefore incorrect to use `Unsafe.getInt` to get a value from the array.

The javadoc of `Unsafe.getObject` essentially points to this.

> Can you provide more details about the VM in question?

It is called [JamaicaVM](https://www.aicas.com/wp/products-services/jamaicavm/).  The implementation does the scaling itself.

>  Have you made the change you request and ran a full build and test cycle on this VM?

No, but I may.  Are there performance tests included?  I want to make sure to not worsen the performance.

> I like opinionated people, I am also opinionated :-)

Same.  Although I change my opinions based on facts and try not to get too attached to them.  (Also not implying that you don't.) ;)

> Using shifts is consistent with the existent code. PRs are welcome if you think there's a better way to do anything.

I am not aware that any VM uses non-powers of 2 for scale.  But in principle this is possible (e.g., to add extra information to references in an array).  In that case, shifts are not going to work.

**Comment by nitsanw** [comment]
@moritz-bruder did you run the tests/build?

**Comment by nitsanw** [comment]
OP lost interest, closing
