### ISSUE TITLE
size() method result over vs under estimation

### ISSUE THREAD

**Issue by fedorovr** [JCTools/JCTools#350]
Hello, thanks for the library implementation!
That is not an issue, but I have a question about `size()` method. As you mentioned in Readme that it is ok to ask questions in issues, I wanna try :)
I am looking at method `IndexedQueueSizeUtil#size()`. It uses 2 indices to calculate it, with some simplifications I consider that producer index stores the position of last added element, consumer index stores index of first candidate to poll (this is based on `BaseMpscLinkedArrayQueue` methods `offer(e)` and `poll()`).
To calculate the size, some reasonable logic is written in lock-free paradigm. But comments confuses me.
```
         * It is possible for a thread to be interrupted or reschedule between the read of the producer and
         * consumer indices, therefore protection is required to ensure size is within valid range. In the
         * event of concurrent polls/offers to this method the size is OVER estimated as we read consumer
         * index BEFORE the producer index.
```
along with this code:
```
(1) long after = iq.lvConsumerIndex();
(2) while (true) {
(3)    final long before = after;
(4)    final long currentProducerIndex = iq.lvProducerIndex();
(5)    after = iq.lvConsumerIndex();
(6)    if (before == after) {
(7)        size = (currentProducerIndex - after);
```
Based on this my assumption that the result of the method may **under** estimate the size, as after reading producer index, line 4, we may insert elements in other threads, before reading consumerIndex at line 5 and returning the result later. So for me this method provides conservative estimation of the size. Why comments declare that size is "OVER estimated"? Where I am wrong? 
Thanks

**Comment by franz1981** [comment]
I see there is another doc error too
"the size is OVER estimated as we read consumer index BEFORE the producer index."

But the code does the opposite... probably worth a fix.
Wanna give it a try with a PR?:) 
We love contribution

**Comment by fedorovr** [comment]
Ok, I will prepare a PR with comments fix in a couple of days

**Comment by nitsanw** [comment]
The way this works is as follows:
```
long consumerIdx1 = lvConsumerIndex();
long producerIdx = lvProducerIndex();
long consumerIdx2 = lvConsumerIndex();
if (consumerIdx1 == consumerIdx2)
  return producerIdx - consumerIdx1; 
```
So the comment is correct in that the consumer index is read **before**, but it is only considered "stable" or "usable" if it is the same as the value observed **after**, reading the producer index. Is it possible that the consumer index moved between reads unobserved? absolutely. We therefore don't know if the stability is indicative of lack of progress, it is more of a way to make a best effort of snapshotting the state of the queue.

**Comment by fedorovr** [comment]
Thanks for clarification of "before" word, Nitsan. But do you agree that quote from code comments "size is OVER estimated" is not correct and may be changed?

**Comment by nitsanw** [comment]
@fedorovr I updated the comment, WDYT?

**Comment by fedorovr** [comment]
It looks nice, thanks.
Just to point that old comment still exists in other places as well. I think they should be updated as well
https://github.com/JCTools/JCTools/blob/66e6cbc9b88e1440a597c803b7df9bd1d60219f6/jctools-core/src/main/java/org/jctools/queues/MpscBlockingConsumerArrayQueue.java#L251
https://github.com/JCTools/JCTools/blob/66e6cbc9b88e1440a597c803b7df9bd1d60219f6/jctools-core/src/main/java/org/jctools/queues/BaseMpscLinkedArrayQueue.java#L206
https://github.com/JCTools/JCTools/blob/66e6cbc9b88e1440a597c803b7df9bd1d60219f6/jctools-core/src/main/java/org/jctools/queues/atomic/BaseMpscLinkedAtomicArrayQueue.java#L320

**Comment by nitsanw** [comment]
I think this should be better now, please have a look :-) Thanks for reporting

**Comment by fedorovr** [comment]
I like how you eliminate code duplication, good work!
