### ISSUE TITLE
Release version for 3.2.0

### ISSUE THREAD

**Issue by dmocek-o** [JCTools/JCTools#351]
Hello.  I'm building JCTools v3.2.0.  When I build, the release version show 3.1.1-SNAPSHOT.jar, not 3.2.0.  I've tried building from both the main repository using the v3.2.0 tag and the JCTools v3.2.0 source.zip release available from the Releases page here on GitHub.  I've followed the instructions on this page: http://jctools.github.io/JCTools/ and on the GitHub page: https://github.com/JCTools/JCTools.  I also tried using 'mvn release:prepare/perform, which asks me the release version, but I would think the POM file would contain the correct version.

How do I build v3.2.0?

**Comment by nitsanw** [comment]
You are building it fine. I have a different pom used to release the project with some extra bits in it. It's not standard and not nice, but it works...
