### ISSUE TITLE
ReadObject comments

### ISSUE THREAD

**Issue by ecki** [JCTools/JCTools#358]
Some of the readObject() methods specify a comment which seems to refer to the wrong type:

    // Read a CHM from a stream

should this be changed into NBHM, NBSI etc?

https://github.com/JCTools/JCTools/blob/a8046376f3df30d5b03a14d11d43199e782e8dad/jctools-core/src/main/java/org/jctools/maps/NonBlockingSetInt.java#L194
https://github.com/JCTools/JCTools/blob/a8046376f3df30d5b03a14d11d43199e782e8dad/jctools-core/src/main/java/org/jctools/maps/NonBlockingIdentityHashMap.java#L1296

https://github.com/JCTools/JCTools/blob/a8046376f3df30d5b03a14d11d43199e782e8dad/jctools-core/src/main/java/org/jctools/maps/NonBlockingHashMapLong.java#L1270

https://github.com/JCTools/JCTools/blob/a8046376f3df30d5b03a14d11d43199e782e8dad/jctools-core/src/main/java/org/jctools/maps/NonBlockingHashMap.java#L1452

**Comment by nitsanw** [comment]
Sounds right!

**Comment by nitsanw** [comment]
PR?

**Comment by ecki** [comment]
I can do that. How about deleting the comment completely?
