### ISSUE TITLE
Unexpected jctools-core 3.3.1-ea release

### ISSUE THREAD

**Issue by SylvainJuge** [JCTools/JCTools#360]
Hi !

We recently got a dependabot PR (https://github.com/elastic/apm-agent-java/pull/2664) to upgrade the previously released `3.3.0` to `3.3.1-ea`.

The meaning of `-ea` suffix and the lack of proper changelog in the PR definitely seems definitely off, and after further investigation:
- the artifact is effectively available [on maven central](https://repo1.maven.org/maven2/org/jctools/jctools-core/3.3.1-ea/)
- there is no related tag nor release in this repository : https://github.com/JCTools/JCTools/releases
- the last commit on `master` branch dates back from few months ago: https://github.com/JCTools/JCTools/commits/master
- the new artifact is 30% larger (~450kb vs ~330kb in 3.3.0).

So, it definitely looks suspicious, in the most optimistic case it's just a release automation issue or unexpectedly pushing an artifact from a local developer machine and ignoring this version is fine, but checking with the person in charge of the release process and/or automation should probably be a good idea.

**Comment by nitsanw** [comment]
Not an issue, I released it to allow some of our customers to play around with unpadded variants before a full release.

**Comment by SylvainJuge** [comment]
Thanks for the clarification @nitsanw !
