### ISSUE TITLE
Missing `Automatic-Module-Name` in 4.0.1 (regression)

### ISSUE THREAD

**Issue by ppkarwasz** [JCTools/JCTools#367]
Version 4.0.1 on Maven Central does not contain an `Automatic-Module-Name` (introduced in #289) in the manifest. I am not able to reproduce the problem compiling the `v4.0.1` tag from sources, but it must be caused by the `maven-jar-plugin` configuration on the host that built the released artifact.

Remark that the currently used `maven-bundle-plugin` version supports the automatic generation of JPMS module descriptors (even on JDK 8) through the `<_jpms-module-info/>` instruction. The generated module descriptor is functionally equivalent to the generated OSGI bundle descriptor. I can provide a PR that modularizes `jctools-core`, `jctools-channels` and `jctools-experimental`.

**Comment by nitsanw** [comment]
@ppkarwasz sorry for long time to reply, would be happy to have a PR!

**Comment by ppkarwasz** [comment]
@nitsanw: I submitted PR #370, which deals with `jctools-core`. If my proposition is acceptable, I can modify in a similar way the other artifacts.
