### ISSUE TITLE
MpscBlockingConsumerArrayQueue need override clear() method to avoid  blocking when queue is empty

### ISSUE THREAD

**Issue by Geker** [JCTools/JCTools#375]
LinkedBlockingQueue&ArrayBlockingQueue both have it own clear() method which would not blocking

**Comment by franz1981** [comment]
Hi @Geker thanks for your interest into JCTools!

The clear method on such queue can be implemented, as the other queues, keep on calling `poll` till return `null`: send a PR if you wish (with some tests)

Please remember, as a user, that given the queue name (`sc` stands for single-consumer, if an existing consumer is blocked awaiting a new element, no other threads can use `clear`; in short, it's admissible to have a single consumer removing elments out of the queue.

**Comment by nitsanw** [comment]
Current impl relies on the default from `AbstractQueue`:
```
    public void clear() {
        while (poll() != null)
            ;
    }
```
The `MpscBlockingConsumerArrayQueue::poll` method is not `blocking` in the `parking` sense. It is blocking in the corner case of spin-waiting for an element when the slot is null but the producer index has moved, which is a rare corner case.

On the other hand, `ArrayBlockingQueue::clear` is clearly blocking:
```
    public void clear() {
        final Object[] items = this.items;
        final ReentrantLock lock = this.lock;
        lock.lock();
// [... more code ...]
```
So I'm not sure what you actually mean here.

@franz1981 is correct that `clear` on `MPSC` is a consumer thread only method.
