### ISSUE TITLE
NonBlockingHashMap's computeIfAbsentc has a bug in a multithreaded environment

### ISSUE THREAD

**Issue by zjf88865** [JCTools/JCTools#376]
This is my code. My local running environment is JDK 1.8, JCTools software version is 4.0.1, operating system is Windows 10, and my computer CPU is 6 cores, 12 threads, and 32GB of memory

```
        <dependency>
            <groupId>org.jctools</groupId>
            <artifactId>jctools-core</artifactId>
            <version>4.0.1</version>
        </dependency>
```
```
private ThreadPoolExecutor threadPoolExecutor = new ThreadPoolExecutor(Runtime.getRuntime().availableProcessors(), 100,
            600, TimeUnit.SECONDS,
            new ArrayBlockingQueue<>(1024), 
            new ThreadPoolExecutor.CallerRunsPolicy());
private NonBlockingHashMap map = new NonBlockingHashMap();
    @Test
    public void nonBlockingHashMapTest() throws InterruptedException {
        for (int i = 0; i < 1000; i++) {
            threadPoolExecutor.execute(() -> {
                map.computeIfAbsent("nonBlockingHashMapTest",domain ->{
                    System.err.println("Display only once？");
                    return "aaa";
                });
            });
        }
    }
```
This program should have been called only once, but it was called many times in a multithreaded environment, which is unreasonable. If I replace NonBlockingHashMap with ConcurrentHashMap at this point, it will return to normal. That is to say, if we follow the ConcurrentHashMap method provided by JDK, it will create many useless objects and make the project difficult to troubleshoot. It can be imagined in millions of lines of code, You will not be able to investigate why you created so many objects without reason

Here is what I printed:
```
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
Display only once？
```

**Comment by xiaoyifang** [comment]
I think you should use `putIfAbsent`  .
computeIfAbsent was inherited from AbstractMap and is not thread-safe

**Comment by franz1981** [comment]
The behaviour is not the same of concurrent hash map but of its interface ie concurrent map.
It means that the lambda can be called by many threads concurrently.

**Comment by ceragon** [comment]
The original design intention of NonBlockingHashMap is that all operations are lock-free implementations. However, the computeIfAbsent method involves transactional operations, and this transaction cannot be implemented without locking. Therefore, JCTools will not solve this problem. 

The operations involved in this transaction are:
1. Determine whether the key exists
2. Generate value through lamdba
3. Put value into the container

NonBlockingHashMap only guarantees that the third step is thread-safe, and only one thread’s third step succeeds.

**Comment by zjf88865** [comment]
> I think you should use `putIfAbsent` . computeIfAbsent was inherited from AbstractMap and is not thread-safe

PutIfAbsent cannot implement my business logic. I need to call my callback function to execute the business logic I specify when my map data does not exist, generate the objects required for the business function, and place them in my map. Obviously, if I use the putIfAbsent() method, I need to create it every time. I don't want to write so much synchronous judgment logic, otherwise I can solve the problem by simply using two synchronized methods, But this is not what I want.

**Comment by zjf88865** [comment]
> computeIfAbsent

If it doesn't support high concurrency, I think the official should label it because I have a deep understanding of it. I found that my data was incorrect, and after a long time of troubleshooting, I realized that this computeIfAbsent() method was a bug

**Comment by zjf88865** [comment]
> `computeIfAbsent`

As a software engineer, I think this is its bug because it did not complete what I wanted as expected. I would rather the computeIfAbsent() method of NonBlockingHashMap be synchronized or locked, so that my business logic will not be wrong. It is obvious that it cannot be implemented, and the premise for software to achieve high concurrency is that its business processing is reliable, I haven't seen any prompts indicating that the method is unavailable or expired, so when I use it, I will notice that it obviously didn't crash when I use it on my website because all my data is incorrect and very difficult to troubleshoot. To achieve lockless modification, this method can be implemented through a callback interface, which I can also accept. However, although there is no lock now, my program data is incorrect. I think this method can refer to the spin lock method, or set a time or spin count or callback method to solve this problem. This is my suggestion, the author should not ignore it, otherwise many people like me will encounter the same problem

**Comment by zjf88865** [comment]
> The original design intention of NonBlockingHashMap is that all operations are lock-free implementations. However, the `computeIfAbsent` method involves transactional operations, and this transaction cannot be implemented without locking. Therefore, JCTools will not solve this problem.
> 
> The operations involved in this transaction are:
> 
> 1. Determine whether the key exists
> 2. Generate value through lamdba
> 3. Put value into the container
> 
> `NonBlockingHashMap` only guarantees that the third step is thread-safe, and only one thread’s third step succeeds.

As a software engineer, I think this is its bug because it did not complete what I wanted as expected. I would rather the computeIfAbsent() method of NonBlockingHashMap be synchronized or locked, so that my business logic will not be wrong. It is obvious that it cannot be implemented, and the premise for software to achieve high concurrency is that its business processing is reliable, I haven't seen any prompts indicating that the method is unavailable or expired, so when I use it, I will notice that it obviously didn't crash when I use it on my website because all my data is incorrect and very difficult to troubleshoot. To achieve lockless modification, this method can be implemented through a callback interface, which I can also accept. However, although there is no lock now, my program data is incorrect. I think this method can refer to the spin lock method, or set a time or spin count or callback method to solve this problem. This is my suggestion, the author should not ignore it, otherwise many people like me will encounter the same problem

**Comment by zjf88865** [comment]
> The behaviour is not the same of concurrent hash map but of its interface ie concurrent map. It means that the lambda can be called by many threads concurrently and/or many times.

If it doesn't support high concurrency, I think the official should label it because I have a deep understanding of it. I found that my data was incorrect, and after a long time of troubleshooting, I realized that this computeIfAbsent() method was a bug

**Comment by ceragon** [comment]
> > The behaviour is not the same of concurrent hash map but of its interface ie concurrent map. It means that the lambda can be called by many threads concurrently and/or many times.
> 
> If it doesn't support high concurrency, I think the official should label it because I have a deep understanding of it. I found that my data was incorrect, and after a long time of troubleshooting, I realized that this computeIfAbsent() method was a bug

To summarize, your complaint is: the implementation of this method is not atomic, and the author should either make it atomic or inform the users. 
First of all, the `computeIfAbsent` method originates from the `ConcurrentMap` interface, so the implementation of `NonBlockingHashMap` actually follows the rules of `ConcurrentMap`. If you carefully read the comments of all methods in `ConcurrentMap`, there is a sentence that says [the action is performed atomically]([ConcurrentMap (Java SE 11 & JDK 11 ) (oracle.com)](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentMap.html)), which means that the implementation of this method must ensure atomicity, such as `putIfAbsent`, `remove`, `replace`, etc. These methods `NonBlockingHashMap` can guarantee their atomic execution. However, this sentence is not in the comment of the computeIfAbsent method, so the implementation of this method does not require atomicity, and only needs to ensure eventual consistency. 
In addition, there is another rule that I don’t know if you are aware of? In NonBlockingHashMap, the remove operation only removes the value, and does not delete the corresponding key value (if the key is an object, then gc cannot recycle it). And this “bug” cannot be solved, which is still related to NonBlockingHashMap being a high-performance lock-free container. 
I suggest you fully understand the characteristics and usage boundaries of this container before deciding whether to apply it to your production environment.

![20230518171949](https://github.com/JCTools/JCTools/assets/6135880/05ea0cc9-e426-43d5-9cc2-000f25bfe27c)

**Comment by franz1981** [comment]
The action is atomic but there is no mention that no others can make it.  What you are describing is an implementation detail of concurrent hash maps that lock the segment which belong the entry. Non blocking hash map is fully unblocking and don't employ that type of behaviour.

**Comment by ben-manes** [comment]
ConcurrentSkipListMap similarly does not provide a computation that blocks and executes atomically. A simple workaround is to use putIfAbsent to store a future, and then compute it outside of the map. See jcip for an example, as it was idiomatic in Java 5.

**Comment by franz1981** [comment]
+100 to @ben-manes to pointing a similar behaviour (will work on my same reproducer, indeed) in the JCL. I can close this as explained
