### ISSUE TITLE
about spmc broadcast problem

### ISSUE THREAD

**Issue by jixiang-yz** [JCTools/JCTools#377]
spmc is somewhat different from my cognition. If poll() method is used, it will only be consumed by one consumer at last. If peek() is used, queue header elements will not be deleted, and queue elements may accumulate at last. (This does not seem to be the case with the channel in rust.)

**Comment by nitsanw** [comment]
- ‘poll’ - next element is removed by one consumer only.
- ‘peek’ - next element is observed, but not removed. Subsequent calls to ‘peek’ will return the same element until a ‘poll’ removes it.

This is the Java interface requirements. Broadcast is not something queues do in Java. You can use the Disruptor as a broadcast channel, or the Agrona LogBuffer IIRC.

**Comment by jixiang-yz** [comment]
thanks
