### ISSUE TITLE
the way of MpscBlockingConsumerArrayQueue provide offerFirst?

### ISSUE THREAD

**Issue by linking12** [JCTools/JCTools#378]
Hi Team:
    Due to the needs of the application, I want to provide the offerFirst method on the basis of MpscBlockingConsumerArrayQueue, is this feasible?

```
public boolean offerFirst(E e) {
        super.offer(e);
        E[] buffer = super.producerBuffer;
        E temp = buffer[buffer.length - 1];
        for (int i = buffer.length - 1; i >= 1; i--) {
            buffer[i] = buffer[i - 1];
        }
        buffer[0] = temp;
        return true;
    }
```

**Comment by nitsanw** [comment]
Hi,
The functionality above is tough to provide and can take long to execute using the following steps:
* A producer slot must be claimed
* The consumer must be blocked (other producers can continue to add elements)
* The elements in the queue are shifted as above(but allowing for wrap around, and can use array copy). The time taken is proportional to the number of elements in the queue.

An alternative would be to push the consumer back and insert into the free slot, but this will require stronger barriers for the consumer everywhere.

There are other ways to provide this, all at some cost to complexity and performance.
