### ISSUE TITLE
Make CACHE_LINE_SIZE configurable

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#38]
e.g., via ``Integer.getInteger(<property>, 64)``

**Comment by nitsanw** [comment]
We have 2 kinds of padding employed in JCTools. One through inheritance which is going to be unaffected by this. The other is through offset calculation which can be helped.

**Comment by ChristianWulf** [comment]
I mean the first one. I see it is currently not possible with Java. Perhaps we can configure it by generating these queues at runtime.
Regarding the second padding: yes, BUFFER_PAD could also be made configurable, although I do not understand why do you choose 32.

**Comment by nitsanw** [comment]
The first case is not covered by this ticket, but the second case will be.
32 * 4 (compressed oop size) = 128, 2 cache line pad.
