### ISSUE TITLE
Unpadded variants could avoid using Unsafe

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#387]
HI @nitsanw !

Now, for convenience we create the unpadded version of the queues out of the Unsafe-based ones, but actually, if users doesn't care about maximum performance by preventing false-sharing, maybe they are NOT interested either to use Unsafe as well, for the same reason. This would make the adoption of such wider, and life of native-image users, happier, wdyt?

**Comment by franz1981** [comment]
I can clearly provide a PR for such if you wish

**Comment by nitsanw** [comment]
We currently have:
* `queues`
* `queues.unpadded`
* `queues.atomic`

You are effectively suggesting a further package of generated code, maybe `queues.atomic.unpadded`? 

To do this we would need to look at the code gen code and generate the code, as well as modify the tests to cover the new variants. This will inflate the jar somewhat, but it's a modest increase to a pretty small jar, and people can alway strip away the extra code if they really care about size.

This is doable, but I'm not going to spend time on it :-), please feel free to PR.

**Comment by jponge** [comment]
I think you can close this one due to #388 being merged 😄 

Could we have a release soon? I'd replace the Unsafe/unpadded queues used in Mutiny, this also would simplify native compilation in Quarkus.
