### ISSUE TITLE
Non-Blocking Doubly-Linked List (Niloufar Shafiei algo)

### ISSUE THREAD

**Issue by benjchristensen** [JCTools/JCTools#39]
I'd be interested in your thoughts on the algorithm presented in this recent paper for a doubly-linked list and how it compares performance-wise with the LinkedList implementations currently in JCTools. I've been struggling to find an actual implementation of this algorithm though the pseudo code in the paper seems thorough. It is honestly a bit beyond my comfort zone hence me reaching out to you before I attempt it to find out if you've already pursued it or have guidance or opinions on it. 

Paper: http://arxiv.org/abs/1408.1935

Thanks

**Comment by nitsanw** [comment]
Closing, no interest in implementing until further news.
