### ISSUE TITLE
release 4.0.3 has been compiled for Java 8

### ISSUE THREAD

**Issue by SylvainJuge** [JCTools/JCTools#392]
The [4.0.3](https://github.com/JCTools/JCTools/releases/tag/v4.0.3) release should have restored compatibility with Java 6.

However, the published artifacts have been compiled for Java 8 as target.

When analyzing the content of https://repo1.maven.org/maven2/org/jctools/jctools-core/4.0.3/jctools-core-4.0.3.jar with `javap` we can see that the bytecode version is 52 (java 8), where 50 (java 6) was expected:

```
Classfile org/jctools/util/Pow2.class
  Last modified Feb 7, 2024; size 1324 bytes
  SHA-256 checksum 64556269c64b5f9eb741082ad927b73c0df91757523f06b3a57157d25861883d
  Compiled from "Pow2.java"
public final class org.jctools.util.Pow2
  minor version: 0
  major version: 52
  flags: (0x0031) ACC_PUBLIC, ACC_FINAL, ACC_SUPER
  this_class: #2                          // org/jctools/util/Pow2
  super_class: #18    
```

**Comment by nitsanw** [comment]
Fixed in v4.0.5

**Comment by SylvainJuge** [comment]
Thanks a lot for the very quick fix here !

While the artifact is effectively available on maven central, there hasn't been a release created on github though. That's definitely a minor annoyance than a real issue, but it currently shows 4.0.3 as the latest release.

**Comment by nitsanw** [comment]
@SylvainJuge sorry about that, will update shortly
