### ISSUE TITLE
Capitalize on new JDK 8 getAndAdd intrinsic for MPSC/SPMC/MPMC bounded queues

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#4]
This should be a relatively small change and should benefit implementations where the CAS loop can be replaced by LOCK XADD. This does however open the door to producers/consumers overstepping and spinning until full/empty queue state is resolved.

**Comment by nitsanw** [comment]
Interesting opportunity on getAndAdd use is explored here:
https://blogs.oracle.com/dave/entry/ptlqueue_a_scalable_bounded_capacity

**Comment by nitsanw** [comment]
Also see Aeron TermAppender for using getAndAdd for an MPSC by using a long to track index + termId and swapping the buffer on overflow

**Comment by felixbarny** [comment]
Thanks to @franz1981's great work we now have an unbounded XADD queue. I was wondering if there were plans for a bounded variant too? Or does the design of the `MpscUnboundedArrayQueue` not translate to bounded queues?

**Comment by franz1981** [comment]
@felixbarny The current design of `MpscUnboundedArrayQueue` doesn't make it a good candidate to develop an XADD variant from it: the TLDR is that even the Aeron TermAppender isn't appropriate to design a (j.u.c) Queue (see https://github.com/real-logic/aeron/pull/403 comments to understand why) and if you look at the relaxed xadd queue on JCTools experiemental it can be hit the same issue of the Aeron TermAppender without the luxury of being unblocked.

ATM I'm not aware of any paper implementing XADD queues if not for "partial" methods (ie methods that won't return until any new element isn't avaialble), @nitsanw can give his view of this, but that's all I know :)

**Comment by felixbarny** [comment]
Sorry, I mean to reference `MpscUnboundedXaddArrayQueue`, not `MpscUnboundedArrayQueue` and whether it would be possible to limit its size. An approximate limit would be fine but I'd like to avoid out of memory situations.

**Comment by nitsanw** [comment]
I think we have now explored some of the options and this vague ticket can be closed
