### ISSUE TITLE
Non-volatile long writes on 32-bit JVM can results in tearing and a bug in SpscArrayQueue::size()

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#41]
While working on some queue related enhancements in RxJava, I've come across a situation where one thread writes a plain long field f1 followed by an ordered write f2 and the other thread volatile reads f2 followed by volatile read of f1. This works on 64 bit JVM but may read an incorrect value on 32 bit JVM. (This gist)[https://gist.github.com/akarnokd/760d4c0669b7caac7a1a] demonstrates the problem. This may happen with SpscArrayQueue.producerIndex but the likelihood is very small because it may present itself only after 1<<32 elements + a concurrent size() call. Is it worth preparing for this issue by lazy-set these longs as well?

**Comment by nitsanw** [comment]
Fixed

**Comment by ChristianWulf** [comment]
We make still the observation that the ``SpScArrayqueue`` initialized with a capacity of 10,000 has a size of 16,384.

Although my following question is not the cause, I need to know: May another, third thread access the ``size()`` method?

**Comment by nitsanw** [comment]
"We make still the observation that the SpScArrayqueue initialized with a capacity of 10,000 has a size of 16,384.
We run our application on an i5-2520M (=64-bit) Windows 7 SP1 machine."
I'm not sure how this is relevant to word tearing or 32 bit JVMs?
Yes, size() can be called from any thread, yes capacity is rounded up to nearest power of 2

**Comment by ChristianWulf** [comment]
Ok, my fault. I forgot the nearest power of 2...
