### ISSUE TITLE
[SP*C Question] Is it safe to have several producer threads accessing SP*C abstractions in sequence ?

### ISSUE THREAD

**Issue by thabach** [JCTools/JCTools#47]
Heya Nitsan 

I was wondering if it was safe to access JCTools's SP*C abstractions sequentially from multiple producers. Those producers would be taking turns and only one would be accessing the queue at any given moment in time. 

Do you keep some internal state, like a producer index, that needs to become visible for subsequent producers and I would need to guarantee visibility by syncing the threads on the outside ? 

Cheers, Christian.

**Comment by nitsanw** [comment]
For single producer queues it is OK to have mutltiple threads offer to the queue only if the queue is handed over from thread to thread in a safe publication manner such that the last offer on one producer HB the first from the next producer.

**Comment by thabach** [comment]
with HB standing in for "happens-before" :ok_hand:
