### ISSUE TITLE
SpmcArrayQueue peek not-null but poll is null?

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#48]
I was using SpmcArrayQueue with a single producer and single consumer and I've noticed that sometimes, I read a non-null value via peek but the subsequent poll returns null. Looking into the class it seems there is a race window spElement and soProducerIndex and reading the various indexes in poll. 

I could change my algorithm to not require peek, but the question is: shouldn't either offer/peek have a happens-before relation (would require soElement) or poll be a bit stronger (lvElement, then wait for index update)?

(Java 1.8u31 64 bit, Win7)

**Comment by nitsanw** [comment]
Can you post a test case?
If your test is excercising multiple consumers than there is no guarantee that poll() will return the same answer as peek() (some other thread may steal the value)
> Looking into the class it seems there is a race window spElement and soProducerIndex and reading the various indexes in poll.
I can't see a race. But maybe I'm missing something here:
spElement -> element is in queue may become visible before producer index is visible
Let's assume that is the case and observe the consumer:
poll()/peek() cannot make progress until producer index for a given element is visible. So the element is in the buffer but no fully published -> return null. This is covered for poll():

        final long currProducerIndexCache = lvProducerIndexCache();
        do {
            currentConsumerIndex = lvConsumerIndex();
            if (currentConsumerIndex >= currProducerIndexCache) {
                long currProducerIndex = lvProducerIndex();
                if (currentConsumerIndex >= currProducerIndex) {
                    return null;
                } else {
                    svProducerIndexCache(currProducerIndex);
                }
            }
        } while (!casHead(currentConsumerIndex, currentConsumerIndex + 1));

And similarly for peek():

final long currProducerIndexCache = lvProducerIndexCache();
        E e;
        do {
            currentConsumerIndex = lvConsumerIndex();
            if (currentConsumerIndex >= currProducerIndexCache) {
                long currProducerIndex = lvProducerIndex();
                if (currentConsumerIndex >= currProducerIndex) {
                    return null;
                } else {
                    svProducerIndexCache(currProducerIndex);
                }
            }
        } while (null == (e = lvElement(calcElementOffset(currentConsumerIndex))));

**Comment by akarnokd** [comment]
Never mind, I spoke to soon. We have an earlier version of Spmc in RxJava where the poll method is just ```return lvElement(calcElementOffset(lvConsumerIndex()));```

**Comment by nitsanw** [comment]
Hmmm.... C&P dependency anyone?

**Comment by akarnokd** [comment]
RxJava expects that if a queue has capacity N, then on a single thread with a single producer, it can offer N elements without the offer returning false.

Regardless, I still think offer/peek has ordering issues. Let's assume I do the following

```
MyObject o = new MyObject();
o.value = 1;
queue.offer(o);
```
If I'm not mistaken, because there is only the final StoreStore barrier in offer, the CPU may freely reorder o.value = 1 and spElement(o), making my object appear half-constructed on a concurrent peek() happening at the right time.

**Comment by nitsanw** [comment]
Does the test fail or pass? When I run it locally it passes...
> the CPU may freely reorder o.value = 1 and spElement(o)

Yes, but
> making my object appear half-constructed on a concurrent peek()

No. What make the published element visible is the producer index write. Until the producer counter is visible the consumer is not allowed to consume the element -> buffer[X] = value HB producerIndex = X.

**Comment by nitsanw** [comment]
"RxJava expects that if a queue has capacity N, then on a single thread with a single producer, it can offer N elements without the offer returning false."
And that is not true for the SPMC queue?

**Comment by akarnokd** [comment]
Thanks for the explanation.

We have some outdated queues in RxJava ported from JCTools, I'd need to recheck all of them.
