### ISSUE TITLE
SpscGrowableArrayQueue capacity is less than requested capacity

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#49]
Users currently expect a power of 2 capacity to end up being the actual resulting capacity of the queue. While this is mildly arbitrary (given that for requested capacity that is less than power of 2 the capacity is rounded up) it is arguably consistent with the following guideline:
Queue capacity >= requested capacity

SpscGrowableArrayQueue breaks that assumption. If requested capacity is <= power of 2 the resulting capacity will be (power of 2 - 1).
To fix the issue I would like to re-structure the queue such that a marker value is used to signal queue is full, but the link to next queue is pointed to in an extra slot.

**Comment by akarnokd** [comment]
In case the capacity is power of 2, the following code I suggested in #45 should utilize the full capacity:

```java
if (null == lvElement(buffer, calcElementOffset(index + 1, mask))) { // buffer is not full, keep last slot for resize indicator
    return writeToQueue(buffer, e, index, offset);
} else if (mask == maxSize) {
    if (null == lvElement(buffer, offset)) { // try using the last slot as there won't be any resize anymore
        return writeToQueue(buffer, e, index, offset);
    }
    // we're full and can't grow
    return false;
}
```
> To fix the issue I would like to re-structure the queue such that a marker value is used to signal queue is full, but the link to next queue is pointed to in an extra slot.
What happens when the producer grows twice while the consumer is still in the first array?

**Comment by nitsanw** [comment]
Fixed and test added

**Comment by nitsanw** [comment]
Test below:

    @Test
    public void testPowerOf2Capacity() {
        assumeThat(spec.isBounded(), is(true));
        int n = Pow2.roundToPowerOfTwo(spec.capacity);

        for (int i = 0; i < n; i++) {
            assertTrue("Failed to insert:"+i,queue.offer(i));
        }
        assertFalse(queue.offer(n));
    }
