### ISSUE TITLE
gpg command required

### ISSUE THREAD

**Issue by georges-gomes** [JCTools/JCTools#50]
Since I updated, it requires gpg to build. (on a Mac)
Normal?

**Comment by nitsanw** [comment]
Only on the release branch where I made my sorry ass attempts at a maven central release...
Can you make sure you are on trunk and post the error?

**Comment by georges-gomes** [comment]
I'm on master

[ERROR] Failed to execute goal
org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on
project jctools-core: Unable to execute gpg command: Error while executing
process. Cannot run program "gpg": error=2, No such file or directory ->
[Help 1]

[ERROR]

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR]

[ERROR] For more information about the errors and possible solutions,
please read the following articles:

[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by nitsanw** [comment]
Dude, I can't reprduce.
Is this still an issue?

**Comment by georges-gomes** [comment]
Hi
Still not working for me but I haven't find time to investigate. you can
close it if nobody complained, I will fix my side later on.
Cheers
GG

**Comment by nitsanw** [comment]
Can you try a clean clone?

**Comment by nitsanw** [comment]
OK, I just tested on a clean clone on:

        $ mvn -version
        Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T22:58:10+02:00)
        Maven home: /home/nitsanw/tools/apache-maven-3.2.3
        Java version: 1.8.0_25, vendor: Oracle Corporation
        Java home: /usr/local/java/jdk1.8.0_25/jre
        Default locale: en_ZA, platform encoding: UTF-8
        OS name: "linux", version: "3.13.0-40-generic", arch: "amd64", family: "unix"
        $ gpg
        gpg: command not found

I explicitly uninstalled gpg to test it, builds fine.
Closing until further evidence...

**Comment by Icronace** [comment]
I have the same failur
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project common: Unable to execute gpg command: Error while executing process. Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified -> [Help 1]

**Comment by nitsanw** [comment]
are you on the 1.0 branch?

**Comment by guidomedina** [comment]
@Icronace don't worry about it, you won't beat my stupidity, one day I coded the following:

```
boolean condition = true;
if (condition) ...
```

Colleagues were laughing, I was planning to put something between these two lines of code but later realized didn't need it and forgot to remove the boolean, it happens to anyone ;-)
