### ISSUE TITLE
Add SNAPSHOT version to mvn repository

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#51]
Btw: increase the version number to 1.1. Currently, a ``mvn package`` generates a 1.0-SNAPSHOT jar.

**Comment by ChristianWulf** [comment]
Have you published the snapshot version to a mvn repository?

**Comment by nitsanw** [comment]
Not planning to have a snapshot published given how unpleasant I find maven publication. If I had someone interested and willing to show some love through maven magic PRs that would be great help.

**Comment by nitsanw** [comment]
I have obviously misunderstood the request here. The master branch maven version has been moved forward, but no publication to the repo is planned. Consider using jit-pack.

**Comment by ChristianWulf** [comment]
I didn't know jit-pack. Thanks for this suggestion!
