### ISSUE TITLE
What about the adaptive backtracking technique at consumer-side?

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#55]
In the paper "BQueue ..." (International Journal of Parallel Programming, 2013), Wang et al. propose an adaptive backtracking technique at the consumer-side to avoid cache trashing due to the shared access on the buffer array. Have you already investigate this technique with ``SpScArrayQueue``?

**Comment by nitsanw** [comment]
Yes, it adds unacceptable latency as a general policy
