### ISSUE TITLE
Batch consuming an MpscLinkedQueue?

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#59]
Would it be possible/feasible to batch consume the contents of an MpscLinkedQueue? I.e., have a method taking a callback which then traverses the links via plain loads until it reaches the producer's node. So instead of polling one by one, it would move the consumer pointer once and not bother nulling out every node's value.

**Comment by nitsanw** [comment]
The volatile load of next is not really an issue, you want to read it from memory, you're not worried about anything else getting repeatedly reloaded.
You could skip nulling out the value, in theory that is only required on the last node in any case. This can be done on the single item poll too but is not a win there(if it's a win at all). The reason not to do it in the normal single item poll is that it would force a load of the producerNode on each item which is a likely cache miss.
IMO there's not a huge win in batching on the un-contended side of the queue, but maybe it's worth the effort.
If I were to invest time in the MpscLinkedQueue I would rather spend it on building a growable variant of it.

**Comment by akarnokd** [comment]
I came up with [this](https://gist.github.com/akarnokd/d4200a28a645bc449757) code and the benchmark results aren't too promising (i7 4790 stock, Windows 7 x64, Java 8u45):
```
Benchmark              Mode  Cnt         Score         Error  Units
MpscQueuePerf.clq     thrpt    5   7664066,284 ?  119763,888  ops/s
MpscQueuePerf.clq1    thrpt    5  22194621,642 ?  270494,889  ops/s
MpscQueuePerf.mpsc7   thrpt    5  14679792,236 ?  512735,509  ops/s
MpscQueuePerf.mpsc71  thrpt    5  33290081,140 ?  564755,822  ops/s
MpscQueuePerf.mpsc7b  thrpt    5  12492237,396 ?  202155,172  ops/s  <--
MpscQueuePerf.mpsc8   thrpt    5  14620079,944 ? 2084588,654  ops/s
MpscQueuePerf.mpsc81  thrpt    5  33384208,228 ?  293470,558  ops/s
MpscQueuePerf.mpsc8b  thrpt    5  12918650,812 ?  595424,507  ops/s  <--
```
It is about 10% slower than polling one by one. My guess is that the extra cost comes from the need to wait for the next pointer to become visible.

**Comment by nitsanw** [comment]
Commented on the gist :)

**Comment by ben-manes** [comment]
> Would it be possible/feasible to batch consume the contents of an MpscLinkedQueue.

Instead of a lambda, a `BlockingQueue#drainTo(Collection)` style would be more performant by stashing into an array and then consuming that. This assumes that the collection is reused by the consumer, so there are no allocations and it stops growing after reaching a steady-state. That still won't offer any meaningful performance gain on the consumer side. Batching on the producer side has a real [impact](https://github.com/ben-manes/caffeine/wiki/Queues), though.

> If I were to invest time in the MpscLinkedQueue I would rather spend it on building > a growable variant of it.

I assume you mean a growable linked array, which is an idea I've mused about for a while but never got to. If I ever did, my plan was to base it off of [Cache-Aware Lock-Free Queues for Multiple Producers/Consumers and Weak Memory Consistency](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=1DDF2867D1B7ECFE894700B9178E11E6?doi=10.1.1.309.6202&rep=rep1&type=pdf) [[slides](http://www.adm.hb.se/~AGD/Presentations/CacheAwareQueue_OPODIS.pdf)]. Once that was working, I'd explore optimizations like recycling arrays once fully consumed.

I suspect that this approach will perform better at low contention, but worse at high contention if a combining arena is used by the node-based data structure. There may be ways to add a similar backoff strategy that compensates for this, but that would require some experimentation.

**Comment by akarnokd** [comment]
@nitsanw I've tried your suggestion but couldn't benchmark it; JHM couldn't finish even the warmup, CPU usage and GC activity spiked. 

@ben-manes copying the values into a collection takes up more memory, implies allocation and adds an unnecessary intermediate step.

**Comment by mjpt777** [comment]
I use both approaches to good effect in Agrona.

https://github.com/real-logic/Agrona/blob/master/src/main/java/uk/co/real_logic/agrona/concurrent/ManyToOneConcurrentArrayQueue.java

The functional interface approach works well with lambda expressions, and the collection approach can reuse an existing collection.

Batch drain can work very well on and MPMC queue to massively reduce contention in my experience.

**Comment by ben-manes** [comment]
@mjpt777 I do the same in my [dynamically striped ring buffer](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedBuffer.java), but for a linked mpsc its hard to determine how batch consumption can be optimized. I thought storing into an array could have some cache benefits, but probably be within the margin of error that it won't be detectably better.

**Comment by mjpt777** [comment]
For MPMC or SPMC the contention focuses on the claim which requires CAS. It is as easy to claim many as one, and thus amortise the cost. The claimed sub-set can the by copied out to the provided collection. I've done this effectively and it can really pay off for work stealing.

**Comment by ben-manes** [comment]
definitely, but what's the benefit for a SC queue?

**Comment by mjpt777** [comment]
Programming model. The win I see in larger applications is that CPUs are at their best when repeating the same task. If you disassociate the queue interaction semantics and instead perform a task over a collection with no memory ordering semantics, or potential for cache misses, then it is more efficient.

Micro benchmarks do not show these sorts of effects. Even on an SPSC queue you have false sharing on the element slots at full and empty and you don't want to pad too much as this washes the cache.

**Comment by ben-manes** [comment]
Okay, so the same rational as why I suggested that using a `drainTo` approach might perform better than the lambda approach @akarnokd prototyped.

**Comment by akarnokd** [comment]
Since this is SC, copying into the buffer would also need pointer chasing followed by an iteration over the collection, followed by a clear to support reuse. So basically:
```java
Collection<T> coll = ...
queue.consume(coll::add);
coll.forEach(action);
coll.clear();
```

**Comment by nitsanw** [comment]
I personally prefer the lambda API for batch operations, both producer and consumer side.
As for the impact, it requires a particular set of experiments to tease out the differences for unbalanced queues (where offer/poll costs are different):
1. Uncontended costs for poll/offer
2. Contended poll/offer costs
3. Simulating expected work either side of the queue (general assumption is that in a real application the queue is mostly empty -> consumer pace > producer pace)
The lambda approach adds a further unknown quantity to the mix with inlining and escape analysis as dramatic optimizations which may or may not happen depending on the lambda and the queue usage...
For SC I think a batch consume is unlikely to make much of a difference, but happy to be proved wrong.
For MC/MP a batch consumer/producer can be a good cure for contention from same side threads. A batch consumer/producer can also improve near empty queue contention.
The batch interfaces require breaking away from the Queue interface. I have a set of interfaces in the experimental module which I plan to finalize in the near future and these methods would find their way there.

**Comment by plokhotnyuk** [comment]
Batch drain can handle up to 350M messages per second from this kind of concurrent structure: https://github.com/plokhotnyuk/actors/blob/6eb4d8c98a1226777293169f8148716ad3d515bc/out2_poolSize1.txt#L1083

**Comment by nitsanw** [comment]
Hi @plokhotnyuk,
This sounds interesting, only I have no idea what queue you are looking at and what benchmark...
More details?

**Comment by plokhotnyuk** [comment]
That was uncontended dequeueing benchmark which tests message handling throughput in a single thread for Scalaz actors.

Here are sources of benchmark and actor handler accordingly:
https://github.com/plokhotnyuk/actors/blob/27ccc651f005d5fa576fe5d74d38fb95a53bb897/src/test/scala/com/github/plokhotnyuk/actors/ScalazActorSpec.scala#L57
https://github.com/scalaz/scalaz/blob/dce8a804cfb79e5904cace2e6655dbc933c1d756/concurrent/src/main/scala/scalaz/concurrent/Actor.scala#L49

Main problem is that speed of enqueueing is in ~7x times less than possible speed of dequeueing (see benchmark `Enqueueing` above). It leads that message handler, that is not loaded by heavy messages processing, contends hardly with producers that decrease speed much less (see results for `Single-producer sending` and `Multi-producer sending`):
https://github.com/plokhotnyuk/actors/blob/6eb4d8c98a1226777293169f8148716ad3d515bc/out2_poolSize1.txt#L1093-L1103

But it allow to reuse same thread to handle messages of 8 actors faster (see `Max throughput` results for batch drain speedup): https://github.com/plokhotnyuk/actors/blob/6eb4d8c98a1226777293169f8148716ad3d515bc/out2_poolSize1.txt#L1105

**Comment by nitsanw** [comment]
Closing this ticket. API for batching now implemented in MessagePassingQueue
