### ISSUE TITLE
Queue implementations without Unsafe

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#61]
In RxJava, we aim to be compatible with platforms that don't support Unsafe so whenever we need to use a queue, we have to check for platfrom support and if not there, revert to classical java queues. However, such platforms (Android) should support the AtomicReferenceArray and AtomicFieldUpdater classes and perhaps we could get some of the missing performance back. 

Is there any plans or interest in doing it within JCTools?

**Comment by nitsanw** [comment]
There's no plan as such, but I estimate we are looking at losing 2 hours of your life to a boring task... I'm happy to put it on the queue and may get to it at some point, or if you want to pitch in with a PR for the queues you care about that's also good.

**Comment by akarnokd** [comment]
Great. I'll post a PR within a few days.

**Comment by plokhotnyuk** [comment]
What about generation of queue implementations?

Let us imagine that we can select desired options:
- allowed number of producer and consumer threads (MPMC, MPSC, SPMC, SPSC);
- underlying data structure (array, list, mixed);
- max size & overflow behavior (unbounded, bounded, overwrite-oldest, etc.);
- forward progress guarantees for producer and consumers (blocking, lock-free and wait-free where it possible);
- API (Java collection, FP-style with handler function, etc.).

And then put them to code generator which will produce implementation, generational (property based) tests and suit of benchmarks.

**Comment by nitsanw** [comment]
Closing as the PR was merged.
@plokhotnyuk we have an issue to track code generating the queues, issue #9

**Comment by plokhotnyuk** [comment]
@nitsanw sorry about that - it definitely worth to be separated issue!

Also I'm not sure that my thoughts was about _runtime_ generation, but if it will work for you then let it be there.

**Comment by nitsanw** [comment]
Not a problem. I'm inclined to support runtime generation because otherwise the jar size will explode, which may be unacceptable for certain users. But if you have a view on that please lets continue the debate on issue #9
