### ISSUE TITLE
Add support for null values

### ISSUE THREAD

**Issue by ChristianWulf** [JCTools/JCTools#64]
Can we replace the representation of an empty slot by a public constant instead of by null? In this way, we could add support for null values and can remove the null check in offer.

**Comment by akarnokd** [comment]
Alternatively, you can wrap the queue into a class that performs this wrapping/unwrapping.

**Comment by ChristianWulf** [comment]
Sure. But this solution causes an unnecessary overhead.

**Comment by nitsanw** [comment]
Either solution causes overhead. Adding null support will tax all implementations for the benefit of the edge case. Null checks are cheaper than normal constant checks.
Apart from that, the poll/peek interface makes it impossible to support null values.
