### ISSUE TITLE
Add a getter for MpscArrayQueue capacity

### ISSUE THREAD

**Issue by RuedigerMoeller** [JCTools/JCTools#66]
Hi, thanks for the great queue impls. I need the capacity of a queue in order to calculate flow-control related stuff.
Also its kind of annoying MpscArrayQueue is a final class. Is this necessary for any reason ?

**Comment by nitsanw** [comment]
It's not final on the mainline, but it is on 1.0:
https://github.com/JCTools/JCTools/blob/7239659ba08e0679e5ca160bbe5f923f07fd4730/jctools-core/src/main/java/org/jctools/queues/MpscArrayQueue.java#L125

Will add capacity to the ArrayQueue base class, so the feature is added to all the ArrayQueues

**Comment by RuedigerMoeller** [comment]
cool, thank you :-). Any mvn release estimation ?

**Comment by nitsanw** [comment]
a week or 2?
I suck at maven-fu, but I can do a jit-pack release pretty easy

**Comment by RuedigerMoeller** [comment]
Was not aware of jitpack !! Not sure wether its possible to publish on maven.org having a jitpack dependency though (probably not).
I for now have workarounded it (by keeping capacity in an extra var along each instance .. hrm), so I can run with 1.0 for some time.  Final is evil keyword :)
