### ISSUE TITLE
Bring over MpscLinkedArrayQueue implementation

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#69]
I've tried to implement a variant to the ```MpscLinkedQueue``` which uses array 'islands' to reduce the allocation frequency and came up with [this](https://gist.github.com/akarnokd/0699387c4ed43f5d4386) ([basic test](https://gist.github.com/akarnokd/a53727e4f01e29e6523e)). 

I haven't benchmarked it yet because I'm not sure it works correctly (despite passing the simple test) and I'd like your opinion and insight on it.

**Comment by nitsanw** [comment]
Looks interesting, much simpler then my SpscUnbounded version, but with the downside of actually allocating the next array even if there's lots of room left in the prev. one. I started looking at building a growable Mpsc version yesterday, but it is slow going as in retrospect I'm not that happy with the Spsc version...
I would rename mask everywhere, there's no mask involved.
       
        if (index < start) {
            throw new IllegalStateException(index + " vs. " + start);
        }

This can happen if the counter wraps(hypothetical, I know). Its more accurate to state (index - start > 0).
    
                ARA2 nextArray = array.next();
                if (nextArray == null) {
                    nextArray = new ARA2(m + 2, end);
                    if (!array.casNext(null, nextArray)) {
                        nextArray = array.next();
                    }
                }

You might be able to avoid redundant allocations by 'winning' the race with a dummy object/flag first, then replacing it with the array and having other threads spin while waiting for it.

                if (array.end < index) {
                    producerArray.compareAndSet(array, nextArray);
                }
A CAS where the result doesn't matter is suspect... but I think it ends up OK even if a producer is very late (i.e. is another array behind)

**Comment by akarnokd** [comment]
Thanks for the feedback. I'll try the single allocator approach.

**Comment by akarnokd** [comment]
I've updated the code and added a [benchmark](https://gist.github.com/akarnokd/618ee49e4e9eb6428f0c).

Results on i7 4790 stock settings, Windows 7 x64, JDK 1.8u45
```
Benchmark            (batch) (producers)  (size)     Score  Score error
MpscLinkedQueue            1           1 1000000    16,793        0,662
MpscLinkedQueue            1           2 1000000     6,469        3,654
MpscLinkedQueue            1           3 1000000     4,291        0,071
MpscLinkedAtomicQueue      1           1 1000000    13,115        0,179
MpscLinkedAtomicQueue      1           2 1000000    10,462        2,436
MpscLinkedAtomicQueue      1           3 1000000     2,697        0,130
ConcurrentLinkedQueue      1           1 1000000    14,411        1,134
ConcurrentLinkedQueue      1           2 1000000     5,252        0,305
ConcurrentLinkedQueue      1           3 1000000     3,392        0,166
MpscArrayQueue          2^20           1 1000000    25,794        1,276
MpscArrayQueue          2^21           2 1000000     9,783        0,578
MpscArrayQueue          2^22           3 1000000     5,073        0,205

MpscLinkedArrayQueue       1           1 1000000     5,394        0,309
MpscLinkedArrayQueue       1           2 1000000     2,471        0,161
MpscLinkedArrayQueue       1           3 1000000     1,502        0,186
MpscLinkedArrayQueueWeak   1           1 1000000     4,908        0,119
MpscLinkedArrayQueueWeak   1           2 1000000     2,574        0,195
MpscLinkedArrayQueueWeak   1           3 1000000     1,383        0,131
```

And as a function of [batch size](https://gist.github.com/akarnokd/e4edfcf341d7ef47198d):

![image](https://cloud.githubusercontent.com/assets/1269832/7749426/b96eb8de-ffcd-11e4-8ff1-58382fdf1f24.png)

In addition, I think ```<=``` works too (haven't benchmarked it):
```
if (array.end <= index) {
    producerArray.compareAndSet(array, nextArray);
}
```
In my understanding, this CAS works because all producers will try to do the same to move the start of the producerArray ahead with the same underlying values.

It is possible to add the usual padding and Unsafe simplifications, but I don't know how the ARA2 could be made into a flat structure: either I use the array reference or I use boxed start/end/nextOffset as part of the array.

**Comment by nitsanw** [comment]
@akarnokd you want to set this up as a PR and we can take it from there? I'll close this as an issue.

**Comment by akarnokd** [comment]
Sure, but not before September from my part.

**Comment by nitsanw** [comment]
Ok, I'll copy paste across if you don't mind? Stick it in experimental and work from there

**Comment by akarnokd** [comment]
Sure, take what you need.

**Comment by nitsanw** [comment]
@akarnokd 
GOD but I am a lazy fucker.
OK, finally took your code and pasted into experimental.
On re-reading it I think it can be improved by following same technique used in MpscGrowable to detect producer allocations and facilitate buffer reuse when possible. It's nice in this case that we get to use getAndAdd, but not sure overall it's worth it.

**Comment by nitsanw** [comment]
Closing as the code has been brought over.

**Comment by akarnokd** [comment]
Great, thanks!
