### ISSUE TITLE
[Channels] Spsc message indicator is not aligned, potentially leading to atomicity issues.

### ISSUE THREAD

**Issue by nitsanw** [JCTools/JCTools#70]
This is currently not an issue as the values for the indicator are:
    private static final int READY_MESSAGE_INDICATOR = 0;
    private static final int BUSY_MESSAGE_INDICATOR = 1;
This means there are no in between torn states to observe.
Going forward if the indicator was to serve further use cases/have more values this can cause issues.
This can also cause performance issues when the header ends up straddling a cache line boundary.

**Comment by franz1981** [comment]
Sorry Nitsan,
I posted it there because i though it was related to the article :P 
And i was not so sure it was really a bug..i miss a lot of details...
Another question...the store of the message between a readAcquire and a readRelease could suffer the same issue? If not..why?

Heelp..:(

**Comment by franz1981** [comment]
I'm an idiot sorry...the issue exists only for memory areas concurrently accessed...but anyway i don't understand why on the constructor there is a cache line alignment instead   of a 8 byte alignment as for the ManyToOneRingBuffer in Agrona...

**Comment by nitsanw** [comment]
OK, so 2 questions, both are good:
1. Are message writes potentially non-atomic? absolutely. There is no alignment guarantee and messages are treated as a 'byte array' in the sense that any write bigger than a byte is not really my problem. Thinking about this issue leads me to believe people might want some alignment guarantees for messages, i.e. each message starts on a cache line aligned location. I'll try and work something into the API.
2. Why does the constructor require cache line alignment? why not 8? The former is stricter than the latter, but both are equally easy/hard to fulfil. I prefer to start my data structure on a cache aligned location. I could work with no alignment requirement at all and just throw away any left over bytes.

**Comment by franz1981** [comment]
Thanks to consider them as good questions :) 
2 cents 4 my thoughs:
1. About the atomicity i though that messages could be treated without considering any issues about atomicity because the barriers issued before writing/reading a slot ensure that only one thread could write/read the data...maybe my assumption is wrong..?
And about the Api i think that " imitation is the best form of flattery" :) indeed maybe the Openhft's data value generator could be a good point to start with...Did you tried it?
2. Ok, now i've understand the reason, thanks :)

**Comment by nitsanw** [comment]
Messages contents are out of bounds of the API, they are acquired and released by the user. Should the user keep references to messages after use then the will be contention and potential issue. Not my problem. Also, if we are on an architecture where unaligned access is an issue, I leave it to the user to worry about. Her/his message contents, her/his problem.
I'll have a look at the OpenHft interface, thanks for the suggestion.

**Comment by franz1981** [comment]
http://grepcode.com/file/repo1.maven.org/maven2/net.openhft/lang/6.6.2/net/openhft/lang/model/DataValueClasses.java/

There are other projects (even that accomplish the "difficult" task to be compliant with c/c++ structs) that generate some kind of flyweights that manage any alignment issue....
These libraries wrap ByteBuffers or similar (custom) abstractions over off/on-heap "byte arrays":if a RingBuffer interface would expose the most common ones (ByteBuffer and/or addresses) the integration with the X/Y/Z library will be a problem only of the user. Maybe the strategy "Her/his message contents, her/his problem" is the right one from an engineering perspective and let the user free to use any means it prefer...BUT as a personal taste, i've never written such a library and i think it would be cool to create (another) one :)
