### ISSUE TITLE
MpscOffHeapFixedSizeRingBuffer.readAcquire publish consumer's index too soon

### ISSUE THREAD

**Issue by franz1981** [JCTools/JCTools#71]
The soConsumerIndex inside the readAcquire publish the consumerIndex before any read of the message content and any write of the message indicator: a writeAcquire could pass the wrap point before a consumer consumer the message. I've adapted the MpscArrayQueue.poll ,splitting it in readAcquire/readRelease and replacing only the lvConsumerIndex of the poll with a lpConsumerIndex and everything seems ok!

**Comment by nitsanw** [comment]
> 
> The soConsumerIndex inside the readAcquire publish the consumerIndex before any read of the message content and any write of the message indicator: a writeAcquire could pass the wrap point before a consumer consumer the message.
> 
That's true. I've mixed up the fast flow and lam port styles of wrap detection here. On FF the consumer of this version is fine, but since the producer is doing a variation on Lamport it end up badly. I think I'll switch it back to FF.

> I've adapted the MpscArrayQueue.poll ,splitting it in readAcquire/readRelease and replacing only the lvConsumerIndex of the poll with a lpConsumerIndex and everything seems ok!
> 
Where is the code?

**Comment by franz1981** [comment]
While i'm playing with JCTools i've rewritten most of the classes for training purposes. I have it in a local repo, if you want i could share all :)

**Comment by nitsanw** [comment]
Rewritten for training?
You mean for studying of for the sake of training other people?
Sharing is encouraged, yes, and bug reports which come with a Pull-Request are always good.

**Comment by franz1981** [comment]
Dear Nitsan, i really want to train someone but first  i've to train...myself! :D
Anyway, my fault: studying is the right word...
I've never done a Pull-Request before...when i'll arrive at home (my dear sources are there) i could do it...
On the blog you share a lot of knowledge...it's the least I can do :+1:

**Comment by nitsanw** [comment]
PRs are a great way to make small contributions, and get recognised for them. Next time you find a bug you think you can fix or demonstrate through a test a PR is a good way to do it. You fork the repo, make the change and push the PR button :-).
