### ISSUE TITLE
Multi-offer for SpscUnbounded with lookahead tips?

### ISSUE THREAD

**Issue by akarnokd** [JCTools/JCTools#76]
I want to use the `SpscUnboundedArrayQueue` to offer a pair of values but poll them in pairs as well. The problem is that if I use two distinct single offers, the receiver end has to wait until both get into the queue before they are polled. This involves looping over queue.size() == 1 if an initial peek succeeded.

I've come up with the following offer method but I still don't quite understand how lookahead works and left it out:

```java
public boolean offer(T first, T second) {
    final AtomicReferenceArray<Object> buffer = producerBuffer;
    final long p = producerIndex;
    final int m = producerMask;
        
    int pi = calcWrappedOffset(p + 1, m);
        
    if (null == lvElement(buffer, pi)) {
        soElement(buffer, pi, second);
        soProducerIndex(p + 2);
        soElement(buffer, pi - 1, first);
    } else {
        final int capacity = buffer.length();
        final AtomicReferenceArray<Object> newBuffer = new AtomicReferenceArray<>(capacity);
        producerBuffer = newBuffer;
            
        soElement(newBuffer, pi, second);// StoreStore
        soElement(newBuffer, pi - 1, first);
        soNext(buffer, newBuffer);
            
        soProducerIndex(p + 2);// this ensures correctness on 32bit platforms
            
        soElement(buffer, pi - 1, HAS_NEXT); // new buffer is visible after element is
    }

    return true;
}
```

The dequeue looks like this:

```java
for (;;) {
   T first = peek();
   if (first == null) break;

   poll();
   T second = poll();
   f.apply(first, second);
}
```

Could you give me some tips about how to put in the lookahead optimization?

**Comment by nitsanw** [comment]
I think (guessing at your usecase) that what you are truely after is a channel that supports objects AND is growable. You want an enqueue/dequeue atomicity for both elements, but you don't want to allocate a wrapper object whenever you want to send a message. I plan to spend some time on the channels after I finish the expanded queue interface work (this week maybe?)
In the mean time, you can extend any SPSC to support your feature by spinning for full reception on the poll and full enqueue on the offer. Yes, there is the possibility of mid-record interruption, but it's quite remote.
Finally, if you want to do as you describe above and have lookahead you will need to ensure the lookahead step is a multiple of the record width. That means the if pIndex < lookAhead then it is safe to put in the next record (assuming all enq/deq are of same width). Rest of the code should be similar.
