### ISSUE TITLE
Subset Interface for Implemented Methods | JCTools specific interface

### ISSUE THREAD

**Issue by sirinath** [JCTools/JCTools#77]
Can you extract interfaces for the implemented subset of the stander interfaces. In case you do not need compatibility with the java collections interfaces users can opt to use it without the risk calling unimplemented code.

**Comment by sirinath** [comment]
Also you could provide a simplistic implementation (need not be efficient) for the unsupported methods and can make them just not encouraged to be used.

**Comment by nitsanw** [comment]
MessagePassingQueue interface is the recommended one.
Is this blocking you somehow? is it nice to have? at this moment this is a documented policy.

**Comment by sirinath** [comment]
If you are using 3rd party libraries unimplemented methods are a bit scary. Even if they do not use a particular functionality that now there is some possibility they just may use this functionality hence preventing you from upgrading. Ideally it will be good to have the interfaces in java.util.concurrent implemented as you can use as a drop in replacement.

**Comment by nitsanw** [comment]
This is a fine theory but I'm asking if this is a blocker for you in a concrete project.
There are no interfaces in j.u.c we're talking about j.u.Queue which is not really designed for concurrent access, hence my reluctance to implement what I consider irrelevant parts of the API.

**Comment by sirinath** [comment]
I have j.u.c data structures which I am looking to replace.

**Comment by nitsanw** [comment]
I'm not sure a separate interface is a good idea as it reduces your ability to switch back (because j.u.c queues don't implement my interface). If you have a concrete example of what you'd like please send it as a PR. Thanks.
