### ISSUE TITLE
Naming - mpmc vs mpsc

### ISSUE THREAD

**Issue by binkley** [JCTools/JCTools#81]
Though clear to the author, it may be difficult for folks new to jctools to keep track of mpmc vs mpsc prefix in the class names.  Likewise for code completion, e.g., searching for "MAQ" finds both "MpmcArrayQueue" and "MpscArrayQueue".  Javadoc on these classes does not help distinguish them either.

I would suggest refactoring classes named with "Mpmc" or "Mpsc" prefix to something more distinct, especially in the first letter.  As they are both multi-producer, perhaps simply "MultiConsumer" and "SingleConsumer"?  (Assuming I understand "mc" and "sc" correctly.)

That I had to recheck that "Mp" was multi-producer and not message-passing (ala "MessagePassingQueue" interface) speaks to this as well.

**Comment by nitsanw** [comment]
I hear you, and I wonder if I am perhaps too immersed in the code base to see the issue.
The acronym-ism is perhaps an inconvenience but this is hard to fix at this point as it will break backward compatibility.
I can offer you 2 workarounds:
1. Use a queue factory to declaratively construct the queues you want.
2. Extend the queue classes locally and name them as you see fit.
