### ISSUE TITLE
Performance regression of QueuePerfTest on JDK 1.8

### ISSUE THREAD

**Issue by openaphid** [JCTools/JCTools#82]
Mac OSX 10.10.5 (14F1021)
iMac (27-inch, Late 2013)
3.5 GHz Intel Core i7

ops of QueuePerfTest on JDK 1.8 is about 25% lower than on JDK 1.6.

```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
capacity:131072 reps:50000000
0 - ops/sec=68,628,132 - MpmcArrayQueue result=777 failed.poll=139 failed.offer=5724
1 - ops/sec=84,857,870 - MpmcArrayQueue result=777 failed.poll=302 failed.offer=0
2 - ops/sec=65,633,545 - MpmcArrayQueue result=777 failed.poll=918 failed.offer=0
3 - ops/sec=64,840,990 - MpmcArrayQueue result=777 failed.poll=574 failed.offer=0
4 - ops/sec=61,928,875 - MpmcArrayQueue result=777 failed.poll=426 failed.offer=0
5 - ops/sec=62,579,347 - MpmcArrayQueue result=777 failed.poll=373 failed.offer=1
6 - ops/sec=65,531,847 - MpmcArrayQueue result=777 failed.poll=808 failed.offer=0
7 - ops/sec=63,255,910 - MpmcArrayQueue result=777 failed.poll=955 failed.offer=1
8 - ops/sec=63,931,103 - MpmcArrayQueue result=777 failed.poll=805 failed.offer=0
9 - ops/sec=62,291,540 - MpmcArrayQueue result=777 failed.poll=1157 failed.offer=1
10 - ops/sec=63,454,408 - MpmcArrayQueue result=777 failed.poll=818 failed.offer=0
11 - ops/sec=65,398,729 - MpmcArrayQueue result=777 failed.poll=772 failed.offer=0
12 - ops/sec=63,300,970 - MpmcArrayQueue result=777 failed.poll=555 failed.offer=0
13 - ops/sec=62,400,248 - MpmcArrayQueue result=777 failed.poll=1733 failed.offer=0
14 - ops/sec=65,504,378 - MpmcArrayQueue result=777 failed.poll=479 failed.offer=0
15 - ops/sec=64,791,094 - MpmcArrayQueue result=777 failed.poll=539 failed.offer=0
16 - ops/sec=66,187,084 - MpmcArrayQueue result=777 failed.poll=429 failed.offer=0
17 - ops/sec=63,240,152 - MpmcArrayQueue result=777 failed.poll=571 failed.offer=0
18 - ops/sec=65,395,049 - MpmcArrayQueue result=777 failed.poll=947 failed.offer=0
19 - ops/sec=62,088,895 - MpmcArrayQueue result=777 failed.poll=2214 failed.offer=0
summary,QueuePerfTest,MpmcArrayQueue,64176100
```

```
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)
capacity:131072 reps:50000000
0 - ops/sec=85,847,521 - MpmcArrayQueue result=777 failed.poll=60 failed.offer=0
1 - ops/sec=84,482,007 - MpmcArrayQueue result=777 failed.poll=74 failed.offer=456
2 - ops/sec=87,609,862 - MpmcArrayQueue result=777 failed.poll=83 failed.offer=0
3 - ops/sec=89,265,470 - MpmcArrayQueue result=777 failed.poll=61 failed.offer=0
4 - ops/sec=88,469,582 - MpmcArrayQueue result=777 failed.poll=59 failed.offer=0
5 - ops/sec=87,319,619 - MpmcArrayQueue result=777 failed.poll=144 failed.offer=0
6 - ops/sec=89,073,369 - MpmcArrayQueue result=777 failed.poll=48 failed.offer=0
7 - ops/sec=88,864,085 - MpmcArrayQueue result=777 failed.poll=61 failed.offer=0
8 - ops/sec=89,155,324 - MpmcArrayQueue result=777 failed.poll=54 failed.offer=0
9 - ops/sec=89,231,060 - MpmcArrayQueue result=777 failed.poll=90 failed.offer=0
10 - ops/sec=87,938,063 - MpmcArrayQueue result=777 failed.poll=65 failed.offer=0
11 - ops/sec=89,270,570 - MpmcArrayQueue result=777 failed.poll=62 failed.offer=0
12 - ops/sec=85,040,666 - MpmcArrayQueue result=777 failed.poll=59 failed.offer=0
13 - ops/sec=87,654,403 - MpmcArrayQueue result=777 failed.poll=58 failed.offer=0
14 - ops/sec=86,533,635 - MpmcArrayQueue result=777 failed.poll=73 failed.offer=0
15 - ops/sec=89,057,028 - MpmcArrayQueue result=777 failed.poll=30 failed.offer=0
16 - ops/sec=89,437,918 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=0
17 - ops/sec=88,470,834 - MpmcArrayQueue result=777 failed.poll=83 failed.offer=0
18 - ops/sec=88,749,414 - MpmcArrayQueue result=777 failed.poll=21 failed.offer=0
19 - ops/sec=86,709,362 - MpmcArrayQueue result=777 failed.poll=91 failed.offer=0
summary,QueuePerfTest,MpmcArrayQueue,87886189
```

**Comment by nitsanw** [comment]
That's interesting.
Some important benchmark hygiene questions:
1. Are the results reproducable over many runs? I would suggest 30 runs of each
2. Is the test topology fixed? by that I mean are the threads on the same core or different cores (no because you are on Mac OS)
3. Is the CPU frequency fixed? this prevents results fluctuating due to turbo boost and temp. throttling related effects. (Again, I don't think you can control that on Mac OS)

**Comment by openaphid** [comment]
Yes, reproducible every time for 30 runs of each

I've tried several times and the results look similar. I'll try to profile it for more details.

**Comment by nitsanw** [comment]
Testing on a server class machine(Intel(R) Xeon(R) CPU E5-2697 v2 @ 2.70GHz) running CentOs:

-bash-4.1$ export JAVA_HOME=/home/nitsanw/jdks/jdk1.6.0_45/
-bash-4.1$ taskset -c 12,13 $JAVA_HOME/bin/java -Dq.type=7 -cp ~/jctools-benchmarks.jar org.jctools.handrolled.throughput.spsc.QueuePerfTest
capacity:131072 reps:50000000
0 - ops/sec=71,559,049 - MpmcArrayQueue result=777 failed.poll=3 failed.offer=1
1 - ops/sec=71,794,307 - MpmcArrayQueue result=777 failed.poll=4 failed.offer=4
2 - ops/sec=73,255,148 - MpmcArrayQueue result=777 failed.poll=141 failed.offer=0
3 - ops/sec=72,567,401 - MpmcArrayQueue result=777 failed.poll=173 failed.offer=0
4 - ops/sec=73,314,571 - MpmcArrayQueue result=777 failed.poll=147 failed.offer=0
5 - ops/sec=73,352,121 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=0
6 - ops/sec=70,886,525 - MpmcArrayQueue result=777 failed.poll=231 failed.offer=0
7 - ops/sec=73,191,161 - MpmcArrayQueue result=777 failed.poll=157 failed.offer=0
8 - ops/sec=71,944,520 - MpmcArrayQueue result=777 failed.poll=172 failed.offer=0
9 - ops/sec=70,927,621 - MpmcArrayQueue result=777 failed.poll=193 failed.offer=0
10 - ops/sec=73,222,693 - MpmcArrayQueue result=777 failed.poll=2 failed.offer=1
11 - ops/sec=72,056,340 - MpmcArrayQueue result=777 failed.poll=203 failed.offer=0
12 - ops/sec=38,923,562 - MpmcArrayQueue result=777 failed.poll=3218 failed.offer=0
13 - ops/sec=56,452,535 - MpmcArrayQueue result=777 failed.poll=1394 failed.offer=0
14 - ops/sec=71,082,736 - MpmcArrayQueue result=777 failed.poll=260 failed.offer=0
15 - ops/sec=73,387,414 - MpmcArrayQueue result=777 failed.poll=162 failed.offer=0
16 - ops/sec=72,078,781 - MpmcArrayQueue result=777 failed.poll=188 failed.offer=0
17 - ops/sec=71,626,360 - MpmcArrayQueue result=777 failed.poll=260 failed.offer=0
18 - ops/sec=70,798,576 - MpmcArrayQueue result=777 failed.poll=208 failed.offer=0
19 - ops/sec=70,666,902 - MpmcArrayQueue result=777 failed.poll=570 failed.offer=0
summary,QueuePerfTest,MpmcArrayQueue,67029589
-bash-4.1$ export JAVA_HOME=/home/nitsanw/jdks/jdk1.8.0_60/
-bash-4.1$ taskset -c 12,13 $JAVA_HOME/bin/java -Dq.type=7 -cp ~/jctools-benchmarks.jar org.jctools.handrolled.throughput.spsc.QueuePerfTest
capacity:131072 reps:50000000
0 - ops/sec=45,946,948 - MpmcArrayQueue result=777 failed.poll=3019 failed.offer=135724
1 - ops/sec=68,524,564 - MpmcArrayQueue result=777 failed.poll=35034 failed.offer=6191
2 - ops/sec=69,239,393 - MpmcArrayQueue result=777 failed.poll=278 failed.offer=0
3 - ops/sec=72,279,583 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=0
4 - ops/sec=72,340,568 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=2
5 - ops/sec=72,244,893 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=1
6 - ops/sec=71,305,967 - MpmcArrayQueue result=777 failed.poll=226 failed.offer=0
7 - ops/sec=71,695,544 - MpmcArrayQueue result=777 failed.poll=167 failed.offer=0
8 - ops/sec=72,124,710 - MpmcArrayQueue result=777 failed.poll=2 failed.offer=1
9 - ops/sec=71,892,603 - MpmcArrayQueue result=777 failed.poll=172 failed.offer=0
10 - ops/sec=71,947,279 - MpmcArrayQueue result=777 failed.poll=144 failed.offer=0
11 - ops/sec=71,772,121 - MpmcArrayQueue result=777 failed.poll=160 failed.offer=0
12 - ops/sec=72,318,638 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=0
13 - ops/sec=71,474,859 - MpmcArrayQueue result=777 failed.poll=185 failed.offer=0
14 - ops/sec=71,879,353 - MpmcArrayQueue result=777 failed.poll=158 failed.offer=0
15 - ops/sec=72,241,109 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=1
16 - ops/sec=71,584,222 - MpmcArrayQueue result=777 failed.poll=5 failed.offer=5
17 - ops/sec=72,249,851 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=0
18 - ops/sec=72,172,506 - MpmcArrayQueue result=777 failed.poll=106 failed.offer=0
19 - ops/sec=72,248,140 - MpmcArrayQueue result=777 failed.poll=1 failed.offer=1
summary,QueuePerfTest,MpmcArrayQueue,71988807

Can't see the issue. Will repeat on a Haswell.

**Comment by nitsanw** [comment]
@openaphid  OK, works for me and not heard back from OP.
