### ISSUE TITLE
Akka mailboxes with JCTools

### ISSUE THREAD

**Issue by guidomedina** [JCTools/JCTools#84]
First let me apologize for using GitHub to send you a question but I couldn't find any other way:

I have the following Akka mailboxes because I believe Akka mailboxes are falling a big behind compared to your implementation, your implementation is always improving so I thought why not delegate the high performance queues to a dependency, at the moment I have replacements for:

* Akka built-in ```SingleConsumerOnlyUnboundedMailbox``` using ``MpscLinkedQueue8``` implementation (I'm using Java 8) 
* I also wanted a Distruptor LMAX approach for a bounded/circular mailbox for specific actors so I ended up using your ```MpscArrayQueue```

General question: **Do you think I came to the right API to create these mailboxes?** I see you have contributed to LMAX disruptor so I'm a bit unsure of which should I stick to for high performance queues.

Here are my two implementations:

**Unbounded mailbox:**
```
public final class MpscUnboundedMessageQueue implements MessageQueue, UnboundedMessageQueueSemantics {

  private final MpscLinkedQueue8<Envelope> queue = new MpscLinkedQueue8<>();

  @Override
  public void enqueue(ActorRef receiver, Envelope handle) {
    queue.offer(handle);
  }

  @Override
  public Envelope dequeue() {
    return queue.poll();
  }

  @Override
  public int numberOfMessages() {
    return queue.size();
  }

  @Override
  public boolean hasMessages() {
    return !queue.isEmpty();
  }

  @Override
  public void cleanUp(ActorRef owner, MessageQueue deadLetters) {
    queue.forEach(envelope -> deadLetters.enqueue(owner, envelope));
  }
}
```

**Bounded RingBuffer approach mailbox:**
```
public final class MpscBoundedMessageQueue implements MessageQueue {

  private final MpscArrayQueue<Envelope> queue;

  public MpscBoundedMessageQueue(int capacity) {
    queue = new MpscArrayQueue<>(capacity);
  }

  @Override
  public void enqueue(ActorRef receiver, Envelope handle) {
    queue.offer(handle);
  }

  @Override
  public Envelope dequeue() {
    return queue.poll();
  }

  @Override
  public int numberOfMessages() {
    return queue.size();
  }

  @Override
  public boolean hasMessages() {
    return !queue.isEmpty();
  }

  @Override
  public void cleanUp(ActorRef owner, MessageQueue deadLetters) {
    queue.forEach(envelope -> deadLetters.enqueue(owner, envelope));
  }
}
```

**Comment by nitsanw** [comment]
NP, this is why the question tag is here!
First, an unfashionable suggestion: you can avoid indirection by extending the queue classes instead of 'decorating' them. You're supplying them via a factory anyhow so I personally don't see the harm.
Otherwise:

 1. Your bounded enqueue seems problematic, what if the offer returns 'false'?
 2. There's a new queue just for you! have you looked at the GrowableMpsc in experimental? will be in next release and combine initially small footprint with much less garbage and better throughput!
 3. You are using offer/poll, could you use the relaxed versions?

Would be great if Akka became a JCTools user :-)

**Comment by guidomedina** [comment]
I think for bounded is OK the following assumptions for my application and from Akka perspective.

* Is OK to return true or false if the queue wasn't full and the offer really happened.
* Is not OK to return true if the offer didn't happen.

I didn't want to relay on eventual consistent behavior with relaxed offer/poll, I suggested Akka guys to take a look at your libraries but another thing I can do is to offer another extension to replace Akka built-in queues which they told me they cannot change so easily due to binary compatibility.

I'll keep you posted, another question, how your bounded implementation compares to LMAX? I wanted exactly what LMAX offers but not the hassle of its implementation, yours seemed to me exactly what I was looking for TBH.

I'm currently extending a FX application, I work for the financial industry and I was able to build a system from scratch by myself and we are moving forward to a more challenging area and need low latency so I might become an Azul customer ;-)

**Comment by guidomedina** [comment]
@nitsanw can I send you the following PRs?

* Maven plugin and dependencies updates.
* Where can I create a constant for ```Runtime.getRuntime().getAvailableProcessors``? It is used at several places I was thinking maybe that should be a constant on a helper class.
* I'm going to run IntelliJ 15.0.3 inspections and might optimize/shrink specific parts of the code.

I'll send you 3 branches so that I don't mix functionalities and it is easier for you to accept/reject.

Let me know about the constant.

**Comment by guidomedina** [comment]
@nitsanw Can the language level be changed to Java 7?

**Comment by nitsanw** [comment]
JCTools core is compiled to Java 1.6, tests/experimental/benchmarks are 1.8. So the hard requirement for 1.8 is only for build time, not runtime.
You'd be surprised at how popular 1.6 is in finance...

**Comment by nitsanw** [comment]
Also, grab me on skype for a more direct chat nitsanw<dot>work

**Comment by nitsanw** [comment]
Runtime.getRuntime().availableProcessors() can move to JvmInfo

**Comment by nitsanw** [comment]
PR was merged and the Q&A is satisfied.
