### ISSUE TITLE
Merge NBHM into JCTools, latest code and compatible licence

### ISSUE THREAD

**Issue by cliffclick** [JCTools/JCTools#88]
Trying to reach the JCTools authors about finding a home for NBHM 

Cliff

**Comment by guidomedina** [comment]
@nitsanw answered at #87 I think he suggested you to just send a PR.

**Comment by vyazelenko** [comment]
both @nitsanw and @RichardWarburton are active discussing this issue in #87

**Comment by nitsanw** [comment]
@cliffclick I extend to you an open invite to come under my roof. You and your maps are welcome :-) 
If you wish to put in a PR, or if you can point to what you consider the definitive version of NBHM I will be very happy to include it in JCTools. You can reach me directly via my twitter account (nitsanw) azul email(same at azulsystems.com) or yahoo email (same at yahoo).
There's 2 aspects needing attention to my mind:

 1. What is the 'right' NHBM version to start with?
 2. What sort of licence does NBHM come under? JCTools is on APLv2, so we'll need to figure out if there's any potential for a mess there.

**Comment by cliffclick** [comment]
Thanks.  As you might can tell from my reply rate, I don't use github as a social media very often.  :-)
I'll put something together and send you a PR
Cliff

**Comment by nitsanw** [comment]
@cliffclick Not a problem, much appreciated.
If you have the time/inclination I would value your feedback on existing JCTools code as well.

**Comment by cliffclick** [comment]
I'm having trouble getting this to build using IDEAJ - endless conflicts between the 1.8 source code and the 1.6 settings IDEAJ is picking up from somewhere.  Any suggestions?

**Comment by guidomedina** [comment]
I had the same problem and I couldn't solve it, you could in your branch convert the 2 or 3 lambdas at the test project to standard call and not commit these files, I couldn't honestly understand why IDEA 15.0.x couldn't handle the source JDK vs test JDK versions TBH.

**Comment by guidomedina** [comment]
When you compile and test with Maven it just works.

**Comment by cliffclick** [comment]
Somehow IDEA gets told these files are 1.6 source-code, but they have 1.8 syntax.
I found & scrubbed all the 1.6 references in IDEA project settings, then it compiled fine.

**Comment by cliffclick** [comment]
Not going to do development using maven...  need a fast edit/compile/debug cycle

**Comment by guidomedina** [comment]
yeah I think once you import you can just tell IDEA that the project is JDK 8, that would do too.

**Comment by nitsanw** [comment]
@cliffclick I use maven to generate the eclipse project.
JCTools compiles for JDK6, but tests, benchmarks and experimental code are allowed to use JDK8 syntax. Maven supports the distinction, but it does confuse IDEs.

**Comment by nitsanw** [comment]
If someone knows a better solution, I'm all ears BTW

**Comment by cliffclick** [comment]
I had to turn off custom-per-module JDK6 language settings (not in the normal IDEA project settings, but in the all-IDEA-project settings).  So it was a little hard to find all the places needing the JDK6->8 touch, but I think I got them all.  Somehow they are getting set anytime IDEA imports the maven POM.  I don't know maven enough to try and hack the POM - especially to make it both Eclipse and IDEA compatible.  For now, I'll just smack IDEA around anytime I need to pull in a new POM.

**Comment by cliffclick** [comment]
Ok, a more serious question.  NBHM from SourceForge included a non-standard build step to produce NonblockingHashtable - a drop-in replacement for the antique Hashtable.  The build step copies NBHMap, changes the parent class (from AbstractMap to Dictionary), and one or 2 other little changes.  Obvious choices are:
1 - Drop NonBlockingHashtable from high_scale_lib
2 - Cut-n-paste NonBlockingHashtable, with the risk that it drifts from NBHMap
3 - Hack a non-standard build-step into maven POM (I have no idea how to do that!)
Thoughts?
Cliff

**Comment by RichardWarburton** [comment]
We have been doing codegen with templates elsewhere in JCTools, perhaps this is a candidate for a similar approach?

**Comment by guidomedina** [comment]
The other thing is that the more bigger the JDK people use the less they remember there is a Hashtable class, you can try to include 1st the NBHM and then see how community re-acts, if nobody needs it then it might as well be an indication people don't actually need it.

And at the same time it gives us all time to figure out the best way, just like a background thread ;-)

**Comment by guidomedina** [comment]
**In other words:** Option 1 and then 3 if needed.

**Comment by cliffclick** [comment]
Just issued pull request.  Pardon any missed steps, this is my first ever pull request.  :-)
Complete up-to-date NBHM, with all tests including performance tests.
No maven integration.
Thanks,
Cliff

**Comment by vyazelenko** [comment]
PR #94 was opened by @cliffclick.

**Comment by nitsanw** [comment]
PR #94 merged to experimental, interested parties please have a look and let me know what you think?
Closing this ticket.
